### ISSUE TITLE
As a user, I want to be able to upload my replays from the RL main menu, so that I can process and view them later.

### ISSUE THREAD

**Issue by chrishollandaise** [stratosphererl/stratosphere#1]
# Acceptance Criteria
- [x] Given that I see a clickable button on the RL main menu
- [x] When I click on the button, I can see it upload to Stratosphere
- [ ] Then I should be able to view it on the website at a later time

# Estimation of Work
- 2 points

# Tasks
- [x] Render a window with no details and only a single button
- [x] Register a notifier with a function designated for uploading replays
- [x] Find the most recent replay file in the file system
- [ ] Fill said function with the necessary functionality to upload replays (Chris)
- [x] Button needs to call a notifier that uploads a replay
- [x] Add a button in the settings menu to toggle replay uploading

# Notes
The button is on the Main menu.
There are some not so userfriendly things about the way I did it. Frankly, I don't think we could make a user-friendly main menu button.

**Comment by chrishollandaise** [comment]
@cchurness Can you clarify what you mean by can't make it user-friendly? Do you mean just for this sprint?

**Comment by chrishollandaise** [comment]
Hey @cchurness, I am reviewing your work, here is my feedback 👍🏻 I haven't done any manual testing yet, just looked at the code.

## Feedback
Awesome job on the overlay. I hope BakkesMod SDK and C++ programming weren't too difficult to get around. Obviously, we are just starting out but this was one of the more technically complicated user stories. I like how you included comments, very helpful in understanding what's going on. I have some minor things that I'd like to point out. 

For lines [28](https://github.com/stratosphererl/stratosphere/blob/caleb-branch/StratospherePlugin/StratospherePlugin/StratospherePlugin.cpp#L28) and [30](https://github.com/stratosphererl/stratosphere/blob/400272a4fe47907e3b8d08acbfff1c311664422b/StratospherePlugin/StratospherePlugin/StratospherePlugin.cpp#L30), I would like you to log the directory. In this instance, it is not as important to have a directory because I don't think the replay file destination changes, but it's good to get in the proper habit. 

In addition, its good practice to generate OS-independent file paths [(Line 23)](https://github.com/stratosphererl/stratosphere/blob/400272a4fe47907e3b8d08acbfff1c311664422b/StratospherePlugin/StratospherePlugin/StratospherePlugin.cpp#L23). While Rocket League doesn't seem to be coming for MacOS and Linux has barely any support, its good to be in the habit of making these file system agnostic. [Here is a resource for how to do that.](https://stackoverflow.com/questions/1056364/how-to-generate-a-os-independent-path-in-c)

## Questions:
- How would another developer go about and build this plugin? Can your plugin in the resource in the README.md or write your own documentation on that?
- How would you go about and test the functionality of the overlay?

## Other remarks:
- In the future, make logs more specific, and detailed. You might want to look into a log manager, especially if we are going to have users publicly test this out. We will also need to look into [categorizing log levels](https://sematext.com/blog/logging-levels/). 


## Tasks summarized:

- [ ] Make file checks OS agnostic.
- [ ] Ensure that logs are descriptive and have all the relevant information needed to do bug testing.

**Comment by cchurness** [comment]
At the time of this comment, I have gotten to make the README (though it may be poor). I have no idea how to test nor what testing libraries c++ provides. It's something for me to research in future sprints.
