### ISSUE TITLE
As an operations engineer, I want to be able to scale my services, so my service doesn't have any downtime.

### ISSUE THREAD

**Issue by chrishollandaise** [stratosphererl/stratosphere#10]
# Acceptance Criteria
- [ ] Given a Stratosphere service
- [ ]  When the service experiences an increase in traffic
- [ ]  Then the service should be able to handle the increased traffic automatically without any downtime

# Estimation of Work
- TBA

# Tasks
- [ ] What needs to get done?

# Notes
I need to look into more orchestration, and how it can load balance or create new instances to split loads.
