### ISSUE TITLE
[EPIC] Replay Service

### ISSUE THREAD

**Issue by chrishollandaise** [stratosphererl/stratosphere#101]
## Description
The replay service, previously known as the parser service, will be responsible for handling replay information. 

Some of the endpoints, do not require an authorization token in order to be used, however others might require this. 

In addition, the processing of the replay (when a user uploads it), will need to be a completely asynchronous task.

## Story(s)
- [x] #102 
- [x] #96 
- [x] #97 
- [x] #98 
- [ ] #99 
- [x] #100 

## What are we planning to do about it?
- [x] Instead of using flask, we should use fastAPI. It is more minimal and better suits this particular service (as we don't need HTML rendering capabilities, etc)
- [ ] In addition, it would be good to use celery as our job queue. We can have a redis container as a broker and backend.
- [ ] This particular service will be in python because of the carball library. 
- [ ] We need to make sure that everything is tested, and checks out. Therefore, we should use pytest as our library.

## How will we measure success?
- All the endpoints are implemented and pass tests.
- Able to persist data.
