### ISSUE TITLE
[EPIC] (Population) Stats Service

### ISSUE THREAD

**Issue by matthew-jugovic** [stratosphererl/stratosphere#106]
## Description
The stats service will be responsible for handling the querying and storage of population statistics as well as have the ability to receive requests for such data and handle them.

Some endpoints will require an authorization token, however the READ endpoints likely will not require such.

The data stored in the stats service will be updated daily (every 24 hours).

## Story(s)
- #107
- #108

## What are we planning to do about it?
- [x] Use FastAPI
- [x] Use PyTest
- [x] ~~Create endpoints for CRUD operations on the population stats~~
- [x] Create database schema to store population stats
- [x] Create init.sql to initialize such a database
- [x] Create a Python script which runs the previous SQL queries once a day and when stats service is turned on

## How will we measure success?
- All endpoints are implemented and pass tests (that is, endpoints are able to be used effectively)
- Population stats DB stores various population data, such as number of users (accounts), number of replays, etc.
- The population stats are updated whenever the stats service is turned on, as well as at 11:55pm of each day (PST or GMT)

**Comment by chrishollandaise** [comment]
So, I see that you do have a python script in your plan! We can talk too about if you have questions
