### ISSUE TITLE
GET stats/replays?{params}

### ISSUE THREAD

**Issue by matthew-jugovic** [stratosphererl/stratosphere#107]
# Acceptance Criteria
- [ ] The API returns the number of replays meeting the query parameters provided
- [ ] At minimum, the following parameters should be implemented:
1. rank=... (avg rank of the replay)
2. map=... (what map the replay was played on)
3. duration=... (length in seconds of the replay)
- [ ] The API returns the appropriate status code for successful requests and error cases
- [ ] Tests are implemented and test appropriately 

# Estimation of Work
- TBA

# Tasks
- [ ] What needs to get done?

# Risks
Not having actual replays to test this against (that is, we currently only have mock replays)

# Notes
- Make sure to return the appropriate status codes

**Comment by chrishollandaise** [comment]
I forget if we could actually get the MMR from the replays, @cchurness what's your opinion on this?

As for the actual endpoint, I agree with the initial route. Getting the statistics of the ranks from replays. But, is there a case where we wouldn't get a rank from a replay? In other words, is there any other data source that we would get rank information? 

You should however change the last part path param (AKA /rank/**{rank}**), instead of a path param. It is better to use a query parameter. This is because you can include multiple optional path parameters (e.g. filtering, sorting).

**Examples: **
`GET /stats/replays?rank=Diamond&map=Hollywood`
`GET /stats/replays?hero=Reinhardt&duration=1200-1800`
`GET /stats/replays?player=JohnDoe&date=2022-01-01`

**TODO**

- [ ] Consider updating the endpoint to use query parameters instead of path parameters. This would allow for more flexible filtering and sorting options, which could be useful in analyzing and comparing replay data.
- [ ] Investigate whether MMR data can be reliably obtained from replay files. If not, consider using another data source to obtain rank information, such as an API that provides current player rankings or data from a game's official website.

**Comment by cchurness** [comment]
> I forget if we could actually get the MMR from the replays, @cchurness what's your opinion on this?
> 
> As for the actual endpoint, I agree with the initial route. Getting the statistics of the ranks from replays. But, is there a case where we wouldn't get a rank from a replay? In other words, is there any other data source that we would get rank information?
> 
> You should however change the last part path param (AKA /rank/**{rank}**), instead of a path param. It is better to use a query parameter. This is because you can include multiple optional path parameters (e.g. filtering, sorting).
> 
> **Examples:** `GET /stats/replays?rank=Diamond&map=Hollywood` `GET /stats/replays?hero=Reinhardt&duration=1200-1800` `GET /stats/replays?player=JohnDoe&date=2022-01-01`
> 
> **TODO**
> 
> * [ ]  Consider updating the endpoint to use query parameters instead of path parameters. This would allow for more flexible filtering and sorting options, which could be useful in analyzing and comparing replay data.
> * [ ]  Investigate whether MMR data can be reliably obtained from replay files.

What we determined about MMR is that we can only get it from the replay if the replay was recorded when BakkesMod was activated. BakkesMod stores the MMR info in the debug section, but without it, we can't get MMR. We can still include searching by rank, some replays just may not be applicable.

**Comment by matthew-jugovic** [comment]
I was anticipating that the Replays service would store all of the data which we have related to a particular replay. That is, while a specific MMR may not be associated with the replay, a particular rank is, as we have done with our mock backend data for coding the frontend. I see no reason that querying by rank should be an issue. We could always get the playing date of a replay and check for each player's rank at that datetime using RLtracker or otherwise to ascertain the average rank of the replay.

I will edit {rank} into a query param

**Comment by chrishollandaise** [comment]
The edits look good. I am thinking about the technical of how the service will aggregate this data. This would require some discussion about how the replays service can allow for this.
