### ISSUE TITLE
GET stats/users?{params}

### ISSUE THREAD

**Issue by matthew-jugovic** [stratosphererl/stratosphere#108]
# Acceptance Criteria
- [ ] The API returns the number of users / profiles meeting the query parameters provided
- [ ] At minimum, the following parameters should be implemented:
1. platform=... (what platform they are associated with)
2. rank=... (most recent rank in a ranked replay, otherwise, unranked)
- [ ] The API returns the appropriate status code for successful requests and error cases
- [ ] Tests are implemented and test appropriately 

# Estimation of Work
- TBA

# Tasks
- [ ] What needs to get done?

# Risks
Not having actual users to test this against

# Notes
- Make sure to return the appropriate status codes

**Comment by chrishollandaise** [comment]
Review, my previous comment on #107, and make adjustments accordingly. In addition, what would the JSON response look like? What sort of things will it return back?
