### ISSUE TITLE
PUT stats/update

### ISSUE THREAD

**Issue by matthew-jugovic** [stratosphererl/stratosphere#109]
# Acceptance Criteria
- [ ] The API updates the data stored in the stats service (total number of replays and users, how many of each per rank or platform, respectively); this is done by querying the replays and users services
- [ ] The API returns the appropriate status code for successful requests and error cases
- [ ] Tests are implemented and test appropriately 

# Estimation of Work
- TBA

# Tasks
- [ ] What needs to get done?

# Risks
Not having actual replays and users data to test this against

# Notes
- Make sure to return the appropriate status codes

**Comment by chrishollandaise** [comment]
On second thought, I know that I said each endpoint needs to have (4 unique actions), but in this case, I don't think we actually need this action at all.

Given that this endpoint takes no inputs (e.g. no query or path params, or a multipart form), I would assume it would need to make other calls on behalf of the caller to other services to "update" the database. In addition, we agreed that this would be on a set daily schedule. Which means that it requires no input from the user at all to perform its action.

Therefore, this should be done as a cron job--think of it as a script that will make the necessary calls. So, instead of this, you should propose a script that will automatically update the database.
