### ISSUE TITLE
POST stats/create

### ISSUE THREAD

**Issue by matthew-jugovic** [stratosphererl/stratosphere#110]
# Acceptance Criteria
- [ ] The API calls for the creation of a new table(s) in the stats service to store population data
- [ ] The API calls for the addition of a row of population stats to store in the created table
- [ ] If adding the above row is not successful, the new table created is deleted
- [ ] This POST is called whenever the stats service is being turned on from being off
- [ ] The API returns the appropriate status code for successful requests and error cases
- [ ] Tests are implemented and test appropriately 

# Estimation of Work
- TBA

# Tasks
- [ ] What needs to get done?

# Risks
Not having actual replays and users data to test this against

# Notes
- Make sure to return the appropriate status codes

**Comment by chrishollandaise** [comment]
@matthew-jugovic, See my comments about #109 #111. I think this would be better if we have a cron job.
