### ISSUE TITLE
DELETE stats/delete

### ISSUE THREAD

**Issue by matthew-jugovic** [stratosphererl/stratosphere#111]
# Acceptance Criteria
- [ ] The API calls for the deletion of the table(s) in the stats service (which includes dropping all of the data in them)
- [ ] This DELETE is called whenever the stats service is being turned off from being on (including if errors / exceptions happen)
- [ ] The API returns the appropriate status code for successful requests and error cases
- [ ] Tests are implemented and test appropriately 

# Estimation of Work
- TBA

# Tasks
- [ ] What needs to get done?

# Risks
Not having actual replays and users data to test this against
How would one implement running a particular piece of code is the server (stats service) crashes?

# Notes
- Make sure to return the appropriate status codes

**Comment by chrishollandaise** [comment]
Why would we drop or delete tables? Also, the only people who would have access to this endpoint would be the admins. I don't see why this needs to exist. See comments #109
