### ISSUE TITLE
[EPIC] User Service

### ISSUE THREAD

**Issue by cchurness** [stratosphererl/stratosphere#112]
## Description
The User Service is tasked with managing endpoints for the transfer of data within the database of user information.

User information includes both basic information (id, platform, username) and also statistical information relating to the replays they've uploaded (wins, losses, goals, goal-shot ratio, etc.). Issue #115 goes into more detail about user statistics.

## Stories
- #113 
- #114
- #115
- #116
- #117

## What are we planning to do about it?
- [x] Use the FastAPI python library for quick and easy endpoint creation and management
- [x] Include unit tests for testing system logic
- [ ] Include integration tests for entire system

## How will we measure success?
- When you can access each endpoint and receive the appropriate response
