### ISSUE TITLE
GET /users/query?{query_string}

### ISSUE THREAD

**Issue by cchurness** [stratosphererl/stratosphere#118]
# Acceptance Criteria
- [ ] Given an application with this endpoint exists
- [ ] When a GET request is made at this endpoint
- [ ] Then a list of users that meet the query parameters is returned

# Estimation of Work
- TBA

# Tasks
- [ ] What needs to get done?

# Notes
- Need to know what information is stored about each user

**Comment by chrishollandaise** [comment]
This would be querying for multiple users correct? how would this be different from #113 in my suggestions?

**Comment by cchurness** [comment]
Updating story #113 to encompass the task of querying.
