### ISSUE TITLE
[SPIKE] - Statistical Visualization

### ISSUE THREAD

**Issue by cchurness** [stratosphererl/stratosphere#119]
# Context
Currently, the only visualized data we have is a poorly put-together heatmap. The purpose of this spike is to consider possible improvements to said heatmap and think of other graphs/plots that we could use to visualize data.

# Timebox
This spike should be completed by 6:00 pm on March 4th, 2023

# Tasks
- [x] Determine what to do about the heatmap
- [x] Determine what visualizations we could use to display replay data
- [x] Create Issues (and possibly a corresponding epic) for creating said visualizations

# Notes
I've already done some thinking on the subject of heat maps; I've come to the conclusion that they are pointless for our project, but close to what we may actually want. Heatmaps are based on the premise that there are lots and lots of data points to plot. The bare minimum amount of data to make a heatmap worth it would be around 50 data points; triple digits to look good; thousands to look immaculate. I would estimate that per each game of rocket league, we collect 6 goals on average (not per team, per game). The original thought behind a heatmap was so players could see trends in their shooting, for the time being, until we collect lots of data, this is unlikely to be useful. However, we can still show where players shoot, it just doesn't need to be in the heatmap format.

**Comment by cchurness** [comment]
## Possible Graph Options
- Bar Graphs (One Bar Per Person) (Do a cool multicolor thing where one color is goals, another is shots, saves, etc.)
  - Ballchasing has bar graphs, just not of this type.
- Optional Actual Heatmap (this would have to be for positions or something we actually have a lot of data for)
  - Ballchasing has this
- Polygon Graph (Points on the polygon represent some data (shots, goals, saves, etc.)
  - Ballchasing does not have this.
- Competitive Bar Graphs (compare team information using sideways bars are "pushing" against each other)
  - This is also used for shots, goals, saves, and assists, but on a team-by-team comparison not player-by-player
  - Ballchasing has this

I would suggest doing the bar graphs and polygon graphs for sure because we would differ from Ballchasing more. Competitive bar graphs are good information even if Ballchasing has them. Positional heatmaps are a "if we have time" thing.

**Comment by cchurness** [comment]
If positional heatmaps become the choice, I make want to base its creation on this:
[https://observablehq.com/@marcel112358/d3-js-heatmap](url)

**Comment by cchurness** [comment]
I don't know what this would be used for, but it looks cool:
[https://observablehq.com/@d3/normalized-stacked-area-chart](url)

**Comment by cchurness** [comment]
As cool as radar charts may be (polygon chart, I finally learned the actual name), the look would look like this for us:
![image](https://user-images.githubusercontent.com/100615693/222927930-1daea563-be65-46e7-966e-54ba7757eedc.png)

If you want it though, look at this link:
[https://github.com/alangrafu/radar-chart-d3](url)
