### ISSUE TITLE
As a user, I want to authenticate myself via Epic on the website, so that I can get access to my account. 

### ISSUE THREAD

**Issue by chrishollandaise** [stratosphererl/stratosphere#12]
# Acceptance Criteria
- [ ] Given that I am a user of the website,
- [ ] When I want to authenticate myself,
- [ ] Then, I should be able to do so via Epic 

# Estimation of Work
- 3 points
- Estimate of work: 4 hours

# Tasks
- [ ] What needs to get done?
- [x] #21

# Notes
- Keep in mind that Epic or Steam will give different information (e.g. username, avatar) about the user when we authorize them. 
- Need to look into their platforms (OAuth) and see what protocols/libraries are needed for authorization
- Do we need anything on the database to end? Cookies? JWT?
