### ISSUE TITLE
[EPIC] Statistical Visualization

### ISSUE THREAD

**Issue by cchurness** [stratosphererl/stratosphere#120]
## Description
The purpose of this epic is to develop fully visualized graphs/maps/imagery that encapsulates the data found in a single replay. Before this epic there was only a heatmap; now we will redo the heatmap and create more visualizations that contribute significantly to the user's experience of our platform.

## Story(s)
- #121 
- #122
- #123
- #136
- [ ] #184

## Roadblocked
- #84

## Affected Personas
- Web developers will be in charge of creating the visualizations and making them interactable
- Website users will get to see match information displayed in a "pretty" way as well as minor interactions

## What are we planning to do about it?
- [x] Put all visualization on their own page on the website (specifically where replay information is to be seen)
- [x] Develop components for each graph/map/image for easier development and reusability
- [x] Use d3.js for each visualization component

## How will we measure success?
1. All the stories are completed
2. The components are viewable to users on the replay page
3. The components use real replay data

**Comment by cchurness** [comment]
Spike related to this epic:
#119
