### ISSUE TITLE
As a User, I want to see bar graphs displaying player data from a replay, so that I can understand what each player in the replay did.

### ISSUE THREAD

**Issue by cchurness** [stratosphererl/stratosphere#121]
# Acceptance Criteria
- [x] Given there is a component tasked with creating a bar graph
- [x] When the component is passed specific data relating to a match
- [x] Then it returns the HTML that visualizes the data using bar graphs

# Estimation of Work
- TBA

# Tasks
- [x] Create a new component
- [x] Define properties based on the below information (Alternatively make it flexible assuming we at least have players)
- [x] Set constraints of graph (how high)
- [x] Create a bar per person
- [x] Make each component of each bar hoverable (to get the value it represents)

# Risks
- What do we do when the player count is unbalanced or 0?

# Notes
## Information Passed To Component
- List of Users
- Each User has...
  - A Name
  - A Team (alternatively we pass two teams each with a list of players)
  - Goals
  - Assists
  - Saves
  - Shots
  - Score? (Likely won't get used, but we may have it anyways)
