### ISSUE TITLE
As a User, I want to competitive bar graphs, so that I can easily compare how one team did against another.

### ISSUE THREAD

**Issue by cchurness** [stratosphererl/stratosphere#122]
# Acceptance Criteria
- [x] Given... When... Then...
- [x] Given that a component exists to create bar graphs
- [x] When team information is passed to the component (or alternatively player info that is processed by the component)
- [x] Then it returns HTML to the user to display said graphs

# Estimation of Work
- TBA

# Tasks
- [x] Create a new component
- [x] Define props of the component
- [x] Convert data to a different format (if necessary)
- [x] Display a horizontal bar for each data component (shots, saves, goals, and assists)
- [x] The bars are interactive to show more complete data

# Risks
- Do we have the information we need for this component separate from the players?
- If we are reliant on players, what happens if we don't have their data?

# Notes
Either that data can be formatted into teams (each team has shots, saves, goals, and assists), or we have lists of players and manage the data and convert it within the component.
