### ISSUE TITLE
As a User, I want to see a heat map of player positions, so that I can better understand where to position.

### ISSUE THREAD

**Issue by cchurness** [stratosphererl/stratosphere#123]
# Acceptance Criteria
- [x] Given we have a component for positional heatmaps
- [x] When passing a list of points (like a lot of points)
- [x] Then the user sees everywhere that was driven
- [x] And overlapping points have a heatmap-type effect

# Estimation of Work
- TBA

# Tasks
- [x] Create a new component
- [x] Start smacking small circles everywhere
- [x] Convert to an image so the HTML isn't too verbose.

# Notes
Should be thinking about what to make the background look like: a picture of the field, the outline of the field, just a box, etc.
