### ISSUE TITLE
[SPIKE] - Consider new logo

### ISSUE THREAD

**Issue by matthew-jugovic** [stratosphererl/stratosphere#124]
# Context
To potentially make a change to our branding which attracts more users to our platform

# Timebox
Midway of sprint (around March 13th)

# Tasks
- [ ] Research platform branding techniques
- [ ] Complete validation discussions with individuals, comparing old and new logos
- [ ] Have different file formats of log: .svg, .ico, .png

# Notes
Link to new logo: https://drive.google.com/file/d/1MdOc2gKE2TYaP8R2KoErp5Ui126-2Ivl/view?usp=sharing

**Comment by matthew-jugovic** [comment]
Main source consulted: https://www.canto.com/blog/methods-of-branding/

Potential branding techniques to use:
- *Personalized*
    - Create an individual connection with customer
- *Co-branding*
    - Team up with another brand to boost market / sales for both
- *Insider*
    - Join relevant groups, social media, share brand / product in authentic way
- *Identification*
    - Users are a main source of advertising, they identify with product and share brand with others, involved community building, having active social media, and potentially encouraging user-generated content
- *Product* 
    - Build effective visuals, logo, color scheme, font, packaging, etc. to entice customer, research how customers are responding to similar products already

Stratosphere platform:
- Will most likely rely on Identification and Product branding techniques
    - Customers will implicitly compare to what they already know that is similar (ballchasing or nothing at all), and decide to continue using our platform based on comparing whether we are better than what they know of. They may then share our platform if we are estimated to be better (due to intuitive design, better visuals, more stats, use of ML models, or etc., etc.)
    - Our platform should evoke certain feelings which may make our platform feel more *professional* or *streamlined* or *useful* than current offerings. This can be done with effective branding on our website, on social media, and while playing using our overlay

TODO: Logo validation with individuals un-initiated with our platform and plans

Logo validation will include:
- Multiple validation sessions (6-10 at least)
- Splitting the sessions between presenting old logo and new logo first and the other second
- Asking validator (interviewee) the emotions and/or thoughts that each logo / logopack evokes
- Also inquiring what product(s) they think the logo and brand name are meant to be for

Other things to consider (though may be outside our scope for now): using branding software, and procuring digital asset management resources

**Comment by matthew-jugovic** [comment]
Discussed with team, now using new logo despite skipping validation process. Link: https://drive.google.com/file/d/1MdOc2gKE2TYaP8R2KoErp5Ui126-2Ivl/view

Our platform's branding and marketing style will likely be along the lines of Insider, Identification, and Product marketing.

Insider: We will position our platform to be easily accessible within places and communities where Rocket League players congregate.

Identification: While we will do the above, doing so in an authentic way is a bit difficult. As such, one of, if not the main source of our platform will / should be from players using our service and sharing it with others. We may want to encourage user-generated content and users supporting development as ways to build further identification with our platform.

Product: Our website should be visually appealing and catch the eye of users so we can be seen not only as technically effective but also aesthetically beautiful. This will engage users in many ways and pull them in. Including allusions to Rocket League on our website will be most useful in our branding, as this is a non-technical way in which we can improve upon what is already out there.
