### ISSUE TITLE
Create new sitemap for website

### ISSUE THREAD

**Issue by matthew-jugovic** [stratosphererl/stratosphere#125]
# Acceptance Criteria
- [ ] Have solid sitemap for website

# Estimation of Work
- Complete by March 7th standup

# Tasks
- [ ] Consider what pages we will want to include on our site
- [ ] Consider how they should best link together so such connections are intuitive and easy for the user to access

# Risks
With limited time for this and upcoming sprints, this sitemap will likely be used for our final product indefinitely. Be thoughtful in your thinking and designing.

# Notes
n/a, refer to tasks

**Comment by matthew-jugovic** [comment]
Website sitemap: https://docs.google.com/drawings/d/1cjWTrHCuCLXwP-jSAe5qLi3Dy0BOmM68__CvWWa823E/edit
