### ISSUE TITLE
Create new wireframe for website

### ISSUE THREAD

**Issue by matthew-jugovic** [stratosphererl/stratosphere#126]
# Acceptance Criteria
- [ ] Have solid wireframe for website

# Estimation of Work
- Complete by March 9th standup

# Tasks
- [ ] Design website wireframe on Figma
- [ ] Consider how to best link pages together in an intuitive fashion
- [ ] Decide on standards (how buttons look, text boxes, when and where to use titles vs subtext, etc.)

# Risks
With limited time for this and upcoming sprints, this wireframe will likely be used for our final product indefinitely. Be thoughtful in your thinking and designing.

# Notes
n/a

**Comment by matthew-jugovic** [comment]
Website wireframe: https://balsamiq.cloud/s6h0nn3/pefjcge/r5A88
