### ISSUE TITLE
Create new mockup for website

### ISSUE THREAD

**Issue by matthew-jugovic** [stratosphererl/stratosphere#127]
# Acceptance Criteria
- [ ] Have solid mockup designed for website

# Estimation of Work
- Complete by March 11th standup

# Tasks
- [ ] Have mockup on Figma which implements previous sitemap and wireframe
- [ ] Follow standards discussed / decided upon when designing wireframe
- [ ] Maintain intuitive and fashionable feel for website

# Risks
With limited time for this and upcoming sprints, this mockup will likely be used for our final product indefinitely. Be thoughtful in your thinking and designing.

# Notes
n/a

**Comment by matthew-jugovic** [comment]
Website mockup: https://www.figma.com/file/Wd7n8nslhvgygiB7wokYIG/Stratosphere-Mockup-(Dark-Mode)?node-id=0%3A1&t=iFzwmeXTKo3tK2kK-0
