### ISSUE TITLE
[EPIC] - Implement website using sitemap, wireframe, and mockup specifications

### ISSUE THREAD

**Issue by matthew-jugovic** [stratosphererl/stratosphere#128]
# Acceptance Criteria
- [ ] Given a user accesses our website, they will be presented with the home page and can access the various parts of our website

# Links
Mockup: https://www.figma.com/file/Wd7n8nslhvgygiB7wokYIG/Stratosphere-Mockup-(Dark-Mode)?node-id=0%3A1&t=ta3As9njABepoM9s-0

# Estimation of Work
- Two weeks (March 13th --> March 26th)

# User Stories
- #137 
- #138 
- #139 
- #140 
- #141 
- #142
- #143 
- #144 
- #145 
- #146 
- #156 
- #147 
- #148 
- #149 
- #150 
- #151 
- #152 
- #153 
- #154 
- #155 

# Tasks
- [x] Add user stories as part of epic after sitemap, wireframe, and mockup have been created
- [ ] Implement website according to sitemap, wireframe, and mockup specifications
- [ ] MUST INCLUDE: uploading data to database (i.e. replay) via API
- [ ] MUST INCLUDE: retrieval of data from API for presentation to user
- [ ] MUST INCLUDE: heatmap and simple statistics visualization

# Risks
This user story will rely on the work of other user stories (ex. visualizations), so be sure to discuss with the individual(s) working on such so that the work from both parts can be brought together effectively and efficiently.

# Notes
The better our website looks the better our project will be seen, even if the backend isn't all that it's cracked up to be.

**Comment by chrishollandaise** [comment]
This will be need to be broken up into separate stories since styling will be a lot of work

**Comment by matthew-jugovic** [comment]
Website mockup: https://www.figma.com/file/Wd7n8nslhvgygiB7wokYIG/Stratosphere-Mockup-(Dark-Mode)?node-id=0%3A1&t=iFzwmeXTKo3tK2kK-0
