### ISSUE TITLE
Get website hosted on simon.plu.edu

### ISSUE THREAD

**Issue by matthew-jugovic** [stratosphererl/stratosphere#129]
# Acceptance Criteria
- [ ] Given a user is connected to the PLU network
- [ ] When the user makes a request to simon.plu.edu
- [ ] Then the user will be able to see the Stratosphere website

# Estimation of Work
- 3 points

# Estimated Installment Date
- Sometime last week of April

# Tasks
- [ ] Convert our frontend hosting to simon.plu.edu
- [ ] Allow for public access via simon.plu.edu
- [ ] Potentially: allow for 24/7 access via simon.plu.edu

# Risks
Will we allow for 24/7 access to our website? There may be issues with converting our files over to simon.plu.edu. Would need light CI/CD implementation.

# Notes
n/a
