### ISSUE TITLE
As a user, I want to see a simple statistical visualizations of my replay, so that I can better understand my play.

### ISSUE THREAD

**Issue by chrishollandaise** [stratosphererl/stratosphere#13]
# Acceptance Criteria
- [ ] Given, a user has a replay of a game
- [ ] When the user goes to the replay page on the website
- [ ] Then, the user should see an heat map and interactive simple statistical visualizations of the replay

# Estimation of Work
- 3 points (5 hours)

# Tasks
- [ ] What needs to get done?

# Notes
- A popular javascript library for complex visualizations is called [D3.js](https://d3js.org/). But, there are others out there.
- It is up to you about the "simple statistical visualizations" bit, whatever you find interesting for now. 
- Page replay and statistics tasks
- Interactivity can be either heatmap or other statistics
