### ISSUE TITLE
For Replay-service GET endpoint(s), convert MMR to its respective rank id integer

### ISSUE THREAD

**Issue by matthew-jugovic** [stratosphererl/stratosphere#131]
# Acceptance Criteria
- [ ] When given an MMR value avgRank from a replay, method convert_to_id will convert that MMR into an int which identifies the rank which the MMR is related to
- [ ] When another service calls the Replay-service to GET a list of replays, the "avgRank" key will be the int associated with the avgRank of the replay, instead of the MMR float, as before

# Estimation of Work
- 3-5 hours?
- Should be quick for handling recent replay data, but will need more work if implementing old ranks (ex. challenger, etc.), or handling changes in MMR boundaries for ranks between seasons

# Tasks
- [ ] Research the MMR boundaries for every RL season, keep those boundaries in mind when implementing the following task
- [ ] Implement convert_to_id method which takes in an MMR float value and converts it to the respective rank int id
- [ ] Consider whether convert_to_id should take a season int parameter to implement different conversions for different seasons
- [ ] Modify Replay-service endpoints so that replay["avgRank"] returns the int created, rather than the MMR float

# Risks
- MMR boundaries for each rank differs between some seasons, thus this story will include some research which best be as accurate as possible
- How should we handle old ranks (such as challenger)? Ignore them for now? If ignoring, create another user story to address that discrepancy

# Notes
n/a
