### ISSUE TITLE
For Replay-service GET endpoint(s), provide season int by converting recorded date into season

### ISSUE THREAD

**Issue by matthew-jugovic** [stratosphererl/stratosphere#132]
# Acceptance Criteria
- [x] When given a recorded date of from a replay, method convert_to_id will convert that date into an int which identifies the season which the replay is related to
- [ ] When another service calls the Replay-service to GET a list of replays, the "season" key will be the int associated with the seaso of the replay

# Estimation of Work
- 2-4 hours?

# Tasks
- [x] Research the date boundaries for every RL season, keep those boundaries in mind when implementing the following task
- [x] Implement convert_to_id method which takes in a date value and converts it to the respective season that date was a part of
- [ ] Modify Replay-service endpoints so that replay["season"] returns the int created

# Risks
Research is included in this story. Be as accurate as possible in the season date ranges

# Notes
n/a
