### ISSUE TITLE
For Replay-service GET endpoint(s), convert arena name IDs into arena num IDs

### ISSUE THREAD

**Issue by matthew-jugovic** [stratosphererl/stratosphere#133]
# Acceptance Criteria
- [ ] When given an arena name from a replay, method convert_to_id will convert that arena name into an int which identifies the arena which the replay was played on

# Estimation of Work
- 2-5 hours?

# Tasks
- [ ] Research the map names which are used in replays for identifying each possible map (ex. a name such as SUBURBS_RAINY_P may identify Beckwith Park, which isn't necessarily intuitive) [note that is not the real name id for Beckwith Park]
- [ ] Implement convert_to_id method which takes in map name id and converts it to the respective map int id
- [ ] Modify Replay-service endpoints so that replay["map"] returns the int created

# Risks
- Research is included in this user story, and it is important to be as accurate as possible

# Notes
n/a
