### ISSUE TITLE
Redo Heatmap (aka make it not a heatmap and share useful info)

### ISSUE THREAD

**Issue by cchurness** [stratosphererl/stratosphere#136]
# Acceptance Criteria
- [x] show some balls on screen
- [x] hover over balls on screen
- [x] show info of goals on screen

# Estimation of Work
- Idk don't ask me

# Tasks
- [x] everythin

# Notes
make it gud
