### ISSUE TITLE
Implement Header component per mockup specification

### ISSUE THREAD

**Issue by matthew-jugovic** [stratosphererl/stratosphere#137]
Link to mockup: https://www.figma.com/file/Wd7n8nslhvgygiB7wokYIG/Stratosphere-Mockup-(Dark-Mode)?node-id=0%3A1&t=iFzwmeXTKo3tK2kK-0

# Acceptance Criteria
- [x] Clicking the Stratosphere logo in the top left sends a user to the HOME page
- [x] Clicking "Upload" in the header sends a user to the UPLOAD page
- [x] Clicking "Browse" in the header sends a user to the BROWSE (general) page
- [x] Clicking "Overlay" in the header sends a user to the OVERLAY page
- [x] Clicking "Statistics" in the header sends a user to the POPULATION STATS page
- [x] Clicking "About" in the header sends a user to the ABOUT page
- [x] Clicking the "Login" button sends a user to the LOGIN page
- [x] Clicking the "Profile" button opens the Profile dropdown as specified in story below
    - #140 
- [x] The header will dynamically present either the "Login" or "Profile" button depending on user's login status

# Estimation of Work
- TBA

# Tasks
- [ ] Implement the Acceptance Criteria as described in Typescript

# Risks
- Making a dropdown shouldn't be too much of a roadblock, but is likely more difficult than other parts of this story
- Also: note that the background of the header is a black to transparent gradient, as follows: #111111 255 alpha --> #111111 0 alpha
- The dropdown, when open, goes past the gradient. Be sure that the height of the gradient stays the same no matter user's logged in state or the dropdown's open/closed state

# Notes
n/a
