### ISSUE TITLE
Implement Footer component per mockup specification

### ISSUE THREAD

**Issue by matthew-jugovic** [stratosphererl/stratosphere#138]
Link to mockup: https://www.figma.com/file/Wd7n8nslhvgygiB7wokYIG/Stratosphere-Mockup-(Dark-Mode)?node-id=0%3A1&t=iFzwmeXTKo3tK2kK-0

# Acceptance Criteria
- [ ] When "footer" is called, returns div meeting the specifications of FOOTER frame in mockup
- [ ] Clicking the Discord logo sends a user to discord.com
- [ ] Clicking the Patreon logo sends a user to patreon.com
- [ ] Clicking the Twitter logo sends a user to twitter.com
- [ ] Clicking the GitHub logo sends a user to https://github.com/stratosphererl/stratosphere
- [ ] Clicking the BakkesMod logo sends a user to https://bakkesplugins.com/
- [ ] Clicking moon logo changes the logo to a sun, and vice versa
- [ ] The background is #111111 255 alpha on the bottom half
- [ ] The background is a gradient #111111 255 alpha to #111111 0 alpha on the top half

# Estimation of Work
- TBA

# Tasks
- [ ] Implement the footer component as described in the Acceptance Criteria and mockup using Typescript

# Risks
TODO in the future: create Discord, Patreon, and Twitter accounts for Stratosphere and link them in the footer

# Notes
n/a
