### ISSUE TITLE
Implement Home page component per mockup specification

### ISSUE THREAD

**Issue by matthew-jugovic** [stratosphererl/stratosphere#139]
Link to mockup: https://www.figma.com/file/Wd7n8nslhvgygiB7wokYIG/Stratosphere-Mockup-(Dark-Mode)?node-id=0%3A1&t=iFzwmeXTKo3tK2kK-0

# Acceptance Criteria
- [x] Create home.tsx which returns a div which meets the specifications for the Home page per the mockup
- [x] Clicking the central "Login" button sends a user to the LOGIN page
- [x] Clicking the "Upload your replay" button sends a user to the UPLOAD page
- [x] Clicking the "Browse other replays" button sends a user to the BROWSE page
- [x] Clicking the "Download our overlay" button sends a user to the OVERLAY page
- [x] The paragraph under "See your opponents?" calls the Stats service to dynamically present the num of replays and users
    - The above relies on #130 
- [x] The header component does not appear until after the central "Login" button is out of the user's screen view

# Estimation of Work
- TBA

# Tasks
- [ ] Implement home.tsx as described above and specified in the mockup
- [ ] Before implementation, research how to dynamic headers and backdrop-filter CSS (see Notes section below)

# Risks
To get the slant for buttons, one is required to use backdrop-filter, which has minimal browser support; is there another option?
Unsure how difficult adding a dynamically appearing header will be; need to research

# Notes
Research: dynamically appearing headers, backdrop-filter documentation (can find example in button CSS on mockup
