### ISSUE TITLE
As a user, I want the overlay to sync game data to Stratosphere and show it, so that I can track trends in my play.

### ISSUE THREAD

**Issue by chrishollandaise** [stratosphererl/stratosphere#14]
# Acceptance Criteria
- [ ] Given the user has installed the Stratosphere overlay
- [ ] When the user starts the game
- [ ] Then the overlay will sync game data to Stratosphere
- [ ] And the overlay will show the game data

# Estimation of Work
- 2 points (4 hours)

# Tasks
- [ ] What needs to get done?

# Notes
- What protocols would the overlay use to communicate with Stratosphere servers (e.g. https, GraphQL)
- What sort of game data makes sense to sync with Stratosphere (e.g. MMR changes on a per game granularity) 
- Track chat potentially?
