### ISSUE TITLE
Implement Profile button component per mockup specification

### ISSUE THREAD

**Issue by matthew-jugovic** [stratosphererl/stratosphere#140]
# Acceptance Criteria
- [x] Clicking the "Profile" button opens a dropdown with the following four options
- [x] Clicking the "Replays" button on the dropdown sends a user to the BROWSE (personal) page; is limited to their replays
- [x] Clicking the "Stats" button on the dropdown sends a user to the INDIVIDUAL STATS page; is limited to their stats only
- [x] Clicking the "Settings" button on the dropdown sends a user to the SETTINGS page
- [x] Clicking the "Logout" button on the dropdown sends a user to the HOME page and returns them to a logged out state

# Estimation of Work
- TBA

# Tasks
- [ ] Implement profile button component

# Risks
n/a

# Notes
n/a
