### ISSUE TITLE
Implement Replay_Data component per mockup specification

### ISSUE THREAD

**Issue by matthew-jugovic** [stratosphererl/stratosphere#141]
# Acceptance Criteria
## General Criteria
- [x] Create replay_data.tsx which has one method that returns div that meets the specs for the Replay Components in mockup
- [ ] "2D View" button --> opens REPLAY page with the 3D view data group button selected and the 2D viewer present
- [ ] "Share" button --> gets address for the REPLAY page of that replay and saves it to clipboard
- [x] Either of the below buttons can be called by the calling statement passing a parameter to replay_data method
## Criteria for When Browsing
- [x] "Full Data" button --> opens REPLAY page with the first data group button selected, replay's graphs and data displayed
## Criteria for When Viewing
- [ ] "Download" button --> sends and saves replay file to user's downloads folder

# Estimation of Work
- TBA

# Tasks
- [ ] Implement replay_data.tsx as specific above and in mockup

# Risks
What is not known? Potential roadblocks?

# Notes
There should be no light gray background in the returned divs as there is in the mockup frames; this is there only to show that the background for the replay components is transparent.
