### ISSUE TITLE
Implement General Browse component per mockup specification

### ISSUE THREAD

**Issue by matthew-jugovic** [stratosphererl/stratosphere#144]
# Acceptance Criteria
- [ ] Gets data from 10 replays and displays them on the page
- [ ] Includes functionality for pagination
- [ ] Allows for searching and filter
- [ ] Searching will only include replays which have the search term in the title
- [ ] Filters will only include replays which meet the search selections chosen by the user
- [ ] Allowed filters:
    - Arena (user can select none, one, or more; if none, no filter applied; if one or more, only replays with those arenas appear)
    - Duration (user can select none, one, or more, etc.; selections are in 1 min ranges (ex. 0-1 mins, 1-2 mins, etc.) up to 20+)
    - Gamemode (can select none, one, or more, similar to Arena)
    - Gametype (can select none, one, or more, similar to Arena)
    - Rank (can select none, one, or more, similar to Arena)
    - Season (can select none, one, or more, similar to Arena)
- [ ] Searching and filtering uses Search & Filter component linked below
    - #143 

# Estimation of Work
- TBA

# Tasks
- [ ] Implement General Browse component per criteria above and mockup specification

# Risks
n/a

# Notes
n/a
