### ISSUE TITLE
Plan out what data to present and how to intuitively group it for replay page

### ISSUE THREAD

**Issue by matthew-jugovic** [stratosphererl/stratosphere#146]
# Acceptance Criteria
- [x] Decided what data should be included on replay page
- [x] Have plans for implementation of graphs for such data
- [x] Plan for how to best group graphs and data together into similar parts

# Estimation of Work
- TBA

# Tasks
- [x] Complete acceptance criteria above

# Risks
n/a

# Notes
n/a
