### ISSUE TITLE
Implement Login page per mockup specification

### ISSUE THREAD

**Issue by matthew-jugovic** [stratosphererl/stratosphere#147]
# Acceptance Criteria
- [x] Create login.tsx which meets the specifications for the Login page per the mockup
- [x] #163
- [x] Clicking on "Epic Games" does nothing yet (TODO: implement Epic Games authentication)

# Estimation of Work
- TBA

# Tasks
- [x] Implement login.tsx as described above and per mockup specification

# Risks
Is the Auth server done? Are we able to receive credentials from Steam?

# Notes
n/a
