### ISSUE TITLE
Implement Upload page per mockup specification

### ISSUE THREAD

**Issue by matthew-jugovic** [stratosphererl/stratosphere#148]
# Acceptance Criteria
- [x] Create upload.tsx which meets the specifications of the Upload frame per the mockup
- [ ] Has functionality to upload (PUT) a replay file to our Replay Service, parse it, and store it
- [x] The user, if they do not leave the page, will be updated via the progress bar and text below it
- [x] Has a video embedded which explains how to upload a replay on our website
    - Relies on #149 

# Estimation of Work
- TBA

# Tasks
- [x] Implement upload.tsx as specified above and per mockup specification

# Risks
n/a

# Notes
n/a
