### ISSUE TITLE
Create video which shows how to upload replays on our website

### ISSUE THREAD

**Issue by matthew-jugovic** [stratosphererl/stratosphere#149]
# Acceptance Criteria
- [ ] Video shows how to upload replays to our website
- [ ] Is hosted on YouTube

# Estimation of Work
- TBA

# Tasks
- [ ] Meet the acceptance criteria above

# Risks
n/a

# Notes
n/a
