### ISSUE TITLE
As a user, I want an MMR trend chart visualization at the end of the game, so that I can track my progress.

### ISSUE THREAD

**Issue by chrishollandaise** [stratosphererl/stratosphere#15]
# Acceptance Criteria
- [x] When a user has completed a game
- [x] Then the user should see an update to their MMR trend chart somehow

# Estimation of Work
- 3 points (4 hours)

# Tasks
- [x] Create vector(s) of floats to store session MMR
- [ ] Push MMR to vector on the match's end
- [x] Create new static window
- [x] Plot histogram of mmrs
- [x] Merge with #14 

# Notes
- The replay uploader may gather similar information regarding the session, it may make sense to do both on the same event.
- Should the trend chart just so how they are currently doing for the game session AKA when the user starts and finishes RL for the day?
- Or should it show also historical trends? How would this be achieved? You probably need to communicate with the database.
- Risk: would it be tracked individually?

**Comment by cchurness** [comment]
I've been doing a bit of thinking and these are my thoughts considering the notes:
 - By default, it shows only the current game session; however, the user can request to view their history.
 At this point, the overlay will make a request to the API to get past session data.
 - The MMR would be uploaded to the overlay after every match, along with the:
   - Session ID
   - Date/time
   - User ID
   - Gamemode
