### ISSUE TITLE
Implement Overlay page per mockup specification

### ISSUE THREAD

**Issue by matthew-jugovic** [stratosphererl/stratosphere#150]
# Acceptance Criteria
- [x] Create overlay.tsx which meets the specifications of the Upload frame per the mockup
- [x] Button will send user to Bakkes plugins
- [x] Has a video embedded which explains how to download and use our overlay
    - Relies on #151 

# Estimation of Work
- TBA

# Tasks
- [x] Meet acceptance criteria

# Risks
n/a

# Notes
n/a
