### ISSUE TITLE
Create video which shows how to download and use our overlay

### ISSUE THREAD

**Issue by matthew-jugovic** [stratosphererl/stratosphere#151]
# Acceptance Criteria
- [ ] Video shows how to download and use our overlay
- [ ] Is hosted on YouTube

# Estimation of Work
- TBA

# Tasks
- [ ] Meet acceptance criteria

# Risks
n/a

# Notes
n/a
