### ISSUE TITLE
Implement About page per mockup specification

### ISSUE THREAD

**Issue by matthew-jugovic** [stratosphererl/stratosphere#152]
# Acceptance Criteria
- [x] Create about.tsx which meets the mockup specification
- [x] Button sends user to discord's website

# Estimation of Work
- TBA

# Tasks
- [x] Meet acceptance criteria

# Risks
n/a

# Notes
n/a
