### ISSUE TITLE
Implement Settings page per mockup specification

### ISSUE THREAD

**Issue by matthew-jugovic** [stratosphererl/stratosphere#153]
# Acceptance Criteria
- [x] Implement settings.tsx per mockup specification
- [x] Button will create a popup asking the user to confirm
- [ ] If popup button is clicked, the user's account will be removed from our User Service and all Replays they have uploaded deleted

# Estimation of Work
- TBA

# Tasks
- [ ] Meet acceptance criteria

# Risks
Is the ability to delete a user already implemented in User Service?
Is the ability to delete a replay already implemented in Replay Service?

# Notes
n/a
