### ISSUE TITLE
Implement Replay page per mockup specification

### ISSUE THREAD

**Issue by matthew-jugovic** [stratosphererl/stratosphere#156]
# Acceptance Criteria
- [x] Implement replay.tsx which meets the REPLAY page specification per mockup
- [x] Clicking the various buttons to the left side will present different data to the user

# Estimation of Work
- TBA

# Tasks
- [x] Meet acceptance criteria

# Risks
n/a

# Notes
n/a
