### ISSUE TITLE
As a user I want the overlay to give me an option to automatically upload replays or choose which relays to upload so that I can have control.

### ISSUE THREAD

**Issue by chrishollandaise** [stratosphererl/stratosphere#16]
# Acceptance Criteria
- [x] Given that the user can see the options of the overlay
- [x] When the user is presented with automatically replay or chooses to upload existing replays
- [x] Then the user should be given be able to check on automatic replay upload or select those replays to upload

# Estimation of Work
- TBA, 3 points total (dropdown 1 and automatic uploads 2)

# Tasks
- [x] Get all the replays from a users directory
- [x] Create a drop-down menu with replays
- [x] Create upload selected button
- [x] Create a checkbox to toggle auto uploading
- [x] Create a hook that gets called on the match end
- [x] Use httpwrapper to send post requests to graphql server

# Notes
- How would the user know about automatic upload without checking the settings page for it? 
- Listening to replay directory for changes
