### ISSUE TITLE
Make reference to number of users and replays dynamic in home.tsx and about.tsx

### ISSUE THREAD

**Issue by matthew-jugovic** [stratosphererl/stratosphere#161]
# Acceptance Criteria
- [ ] When a user views either the home or about page, have the references in the text referring to the number of users and replays on our site display the actual number present on our site

# Estimation of Work
- TBA

# Tasks
For both home.tsx and replay.tsx:
- [ ] Call stats service for number of users and number of replays
- [ ] Dynamically present the two numbers in the text of each page

# Risks
None

# Notes
n/a
