### ISSUE TITLE
As a machine learning engineer, I want a lot of replay data, so that I can make accurate models.

### ISSUE THREAD

**Issue by chrishollandaise** [stratosphererl/stratosphere#17]
# Acceptance Criteria
- [ ] Given that I have a data shortage problem
- [ ] When finding a way to get data
- [ ] Then I can make accurate models

# Estimation of Work
- 5 point ( 2 hours)

# Tasks
- [ ] What needs to get done?

# Notes
- Ball chasing has a lot of replays. Need to use the API to download replays, and also ensure that we can get all the categories of that match (e.g. whether it was a pro match, the map, the game mode, players, etc) up front AKA, not from the replay.
- In Python, there is Selenium, Scrapy, Beautiful Soup, and other libraries. Depends on the complexity of the website.
- Scraping. Making sure you don't make redudant requests
