### ISSUE TITLE
As a User, I want to evaluate the chance of winning, so that I can understand the "value" of the game at a specific frame.

### ISSUE THREAD

**Issue by cchurness** [stratosphererl/stratosphere#178]
# Acceptance Criteria
- [ ] When a post request is made that uploads a specific frame's data
- [ ] Then That frame data will evaluate the win chance of both team's

# Estimation of Work
- TBA

# Tasks
- [x] #179
- [ ] Create the endpoint: "/win-percent/{game_mode}"
- [ ] Evaluate both team's chance of winning
- [ ] Return the softmax output of both evaluations

# Notes
1v1, 2v2, and 3v3
