### ISSUE TITLE
Train Win Chance Model

### ISSUE THREAD

**Issue by cchurness** [stratosphererl/stratosphere#179]
# Tasks
- [ ] Create datasets for 1v1, 2v2, and 3v3
- [ ] Try different classification techniques
- [ ] Create 3 models for each gamemode

# Notes
Target: Win/Loss
All ranks (maybe include rank as an attribute)
