### ISSUE TITLE
As a user, I want to a prediction of me or my play from publicly accessible data, so that I can understand my playstyle.

### ISSUE THREAD

**Issue by chrishollandaise** [stratosphererl/stratosphere#19]
# Acceptance Criteria
- [ ] Given a player's record
- [ ] When the player wants a prediction about their record
- [ ] Then the model should generate a prediction about the player

# Estimation of Work
- TBA

# Tasks
- [ ] What needs to get done?

# Notes
- What sort of predictions make sense from publicly accessible API (e.g. Tracker.gg?)
