### ISSUE TITLE
As a developer, I want to parse RL replay files, so that its easier to wrangle with its data.

### ISSUE THREAD

**Issue by chrishollandaise** [stratosphererl/stratosphere#2]
# Acceptance Criteria
- [ ] Given that I have a correctly formatted replay file
- [ ] When I input my replay file to the RL parser service
- [ ] Then I should be able to retrieve human-readable data associated with it

# Estimation of Work
- TBA

# Tasks
- [ ] What needs to get done?

# Notes
The replay parser service will input an RL replay file and output another format [(e.g. JSON, XML, CSV, YAML)](https://www.wikiwand.com/en/List_of_open_file_formats#section_Other). Make a choice about which file type you want to use and know why.

It is suggested that after the completion of this story, you should have a basic understanding of RLs replay files and the kind of data that exists with them, it'll be helpful to be able to document resources or have explanations to help future developers that are unfamiliar.

Decision on using a third-party replay parser or making an in-house. If you do use a third-party parser, are there any differences between different parsers (e.g. performance, extra calculated data, maintainability, regularly updated)?  The choice is yours to make.
