### ISSUE TITLE
As a user, I want to have Stratosphere publicly available on the campus, so that I can use it anywhere.

### ISSUE THREAD

**Issue by chrishollandaise** [stratosphererl/stratosphere#20]
# Acceptance Criteria
- [ ] Given that I am a user or visitor,
- [ ] When I go to the Stratosphere website or try to communicate via an overlay,
- [ ] Then I should be able to access it on PLU

# Estimation of Work
- 3 hours (2 days)

# Tasks
- [ ] Create a pipeline that is able to update docker containers on server containers.
- [ ] Check out the IP address to access it on campus.

# Notes
- We will need to set up the dockers on our server.
