### ISSUE TITLE
As a website user, I would like to choose between dark/light theme on website, so that I can change the theme to my liking.

### ISSUE THREAD

**Issue by matt89201824** [stratosphererl/stratosphere#22]
# Acceptance Criteria
- [ ] A visitor to the website can click a button to switch between a dark and light background

# Estimation of Work
- TBA

# Tasks
- [ ] Add discrete button to either main page or all pages of website
- [ ] If the user is currently in light mode, clicking the button switches to dark; vice versa

# Risks
- This story may require having two html files stored for the same page (one for light mode and dark mode respectively), which may present a storage issue if we have a lot of pages; I imagine CSS would allow this to be implemented with a rgb variable change though

# Notes
- Know how to make a button call a new html page
