### ISSUE TITLE
As a website developer, I want session to be collected each time someone access the website, so that I can gain insight into what parts of the website are used more often and by which users

### ISSUE THREAD

**Issue by matt89201824** [stratosphererl/stratosphere#23]
# Acceptance Criteria
- [ ] When a user starts a browsing session of our website, a new row is entered into a database relation (ex. "session_data")
- [ ] As the user clicks buttons on the site, each button click iterates its respective column value in that row of session data
- [ ] Some user data is also present, including acct name (or none), approximate location (ex. country), etc.
- [ ] When the user disconnects from the website, that row of session data is finalized

# Estimation of Work
- TBA

# Tasks
- [ ] Gathering of what data we would want collected about browsing sessions and users
- [ ] Creation of database schema for new relation
- [ ] Writing of PostgreSQL commands for data entry
- [ ] Communication between website and database through API whenever a button is clicked

# Risks
This is likely to pose an issue long-term, especially if we start getting a lot of traffic daily; to maintain all collected data would be costly

# Notes
N/A
