### ISSUE TITLE
As a general user, I want to see post-game and on-website identification of player traits, so that I can see what types of playstyles I work well with and not so well with.

### ISSUE THREAD

**Issue by matt89201824** [stratosphererl/stratosphere#24]
# Acceptance Criteria
- [ ] Website: when given a replay, each player in the replay is assigned one or more player traits via ML model
- [ ] Overlay: after a match is concluded, each player in the match is assigned one or more player traits via ML model

# Estimation of Work
- 20 points

# Tasks
- [ ] Research on what types of playstyles the RL user base could be split into (this is largely subjective?)
- [ ] Manually iterating through replays to assign playstyles to players for training data
- [ ] Splitting collected data into training, testing, and validation sets
- [ ] Training and testing various ML models to see which may work best for our needs (trial and error)
- [ ] Potentially: gaining user / outside feedback on whether our model feels accurate and useful

# Risks
Lots of time needs to be spent simply manually iterating through replays to identify playstyles
How we are to split the playstyles of RL players into groups is largely subjective; we could make it as simple as offensive/defensive, or go crazy with it and have something like the following: offensive rotational freestyler w/ poor goalkeeping; the previous is too bland, the other sounds good but may be too difficult

# Notes
Lots of time is needed for manual iteration, training and testing ML models, etc.
Using an ML model which clusters without labeled data (unsupervised learning) may be best to help us group playstyles
