### ISSUE TITLE
As a website user, I want to be able to identify tricks in my play, so that I can better analyze my technique.

### ISSUE THREAD

**Issue by chrishollandaise** [stratosphererl/stratosphere#25]
# Acceptance Criteria
- [ ] ML: Model can differentiate and label known moves
- [ ] Web: Able to see the moves/tricks that were present in that replay 

# Estimation of Work
- TBA

# Tasks
- [ ] What needs to get done?

# Risks
It is a bigger project, this might even be classified as [an epic](https://www.atlassian.com/agile/project-management/epics#:~:text=Summary%3A%20An%20agile%20epic%20is,epic%20serves%20to%20manage%20tasks.). Because there would 

# Notes
Currently, calculated.gg looks to have a system where they can identify tricks/mechanics used by the player. This may or may not be helpful if the player can start aggregating what moves led to what scenarios.

I can imagine that just like critical moments if we can start classifying what certain x,y,z coordination and rotation moments are associated with what moves, it could help in classifying it.

**Comment by matt89201824** [comment]
Do remember, for this issue, we may have a lot of mechanics which we could identify manually (ex. if player hits ball, the ball hits backboard, and the player then hits the ball in without x seconds, it is a double-tap goal
