### ISSUE TITLE
As a website user, I want to see a goal heat map, so that I can understand where I or other players tend to shoot.

### ISSUE THREAD

**Issue by chrishollandaise** [stratosphererl/stratosphere#26]
# Acceptance Criteria
- [x] Given a replay of a game on the website,
- [x] When the user sees the component,
- [x] Then they should be able to see where the balls went on a per player or aggregate basis

# Estimation of Work
- 5 hours (2-3 days), assuming we have the information

# Tasks
- [x] Create a heatmap component
- [x] That takes in a variety of props including data
- [x] Displays an image of a goal
- [x] And displays a density chart of all the points from given data

# Risks
- What counts as a shot on the goal? Where do the field stop and the goal start?
- How does Rocket League determine a shot? Do we want to go with that? (aka Counting shots that weren't registered as shots)
- D3.js

# Notes
This can be a helpful metric once the user gets enough replays, and get an average.
Also account for misses or those that are not accounted
Have an option for a velocity vector on the ball, where it is predicted to go
