### ISSUE TITLE
As a user, I want to see what position players are in at a particular point in a replay, so that I can understand formations and rotations.

### ISSUE THREAD

**Issue by cchurness** [stratosphererl/stratosphere#28]
# Acceptance Criteria
- [ ] Must be able to select a frame from a replay
- [ ] Send data to the Machine learning model
- [ ] Present relevant data from the ML model about each player

# Estimation of Work
- TBA

# Tasks
- [ ] What needs to get done?

# Risks
We need to know how to do the ML model if we want to use that at all.
To be easily interactable from the user's perspective, you will want to see the 3D replay and capture a frame.

# Notes
This might not have to be through the ML component if that's too far down the road; it could be based on position relative to your goal (aka first man, second man, and third man; or offensive, defensive).
