### ISSUE TITLE
As a user, I want to see a 3D representation of a replay, so that I can better understand the analysis of a match by correlating it to the match itself.

### ISSUE THREAD

**Issue by cchurness** [stratosphererl/stratosphere#29]
# Acceptance Criteria
- [ ] See a 3D model of a replay at whatever frame of my choosing
- [ ] A play/pause button to move the replay forward
- [ ] Timeline to select which frame to show
- [ ] Timeline that shows relevant points in the game
- [ ] Ability to change perspectives in the replay

# Estimation of Work
- TBA

# Tasks
- [ ] What needs to get done?

# Risks
Understand game data regarding frames (parsing problem).
Getting models for Cars and ball (could just be boxes and spheres for this issue)

# Notes
It's a lot of work that may be split over a couple of issues
