### ISSUE TITLE
As a user, I want to upload a RL replay on the web, so that I can see numbers about my play.

### ISSUE THREAD

**Issue by chrishollandaise** [stratosphererl/stratosphere#3]
# Acceptance Criteria
- [x] Given that I go to the website on my browser
- [x] When I upload a valid RL replay file
- [ ] I should see it upload and display numbers about my match

# Estimation of Work
- 1 point

# Tasks
- [x] Create a place to select our replay file to upload
- [ ] Upload file to parser/database
- [x] Display information about replay

# Notes
What happens when the user is waiting? What if the replay file is not valid?
