### ISSUE TITLE
As a user, I want to search and use filters to find replays, so that I can learn from other player's games as well as my own.

### ISSUE THREAD

**Issue by cchurness** [stratosphererl/stratosphere#30]
# Acceptance Criteria
- [x] Have database in parser/db with mock data
- [ ] Frontend w/ more filtering options, and can search through replays (using mock data)
- [ ] Implement API call to database w/ Docker (talk to Chris)
-----
- [x] Search for replays using keywords
- [x] Set filter options to receive relevant replays
- [x] Select the replay I want to look at

# Estimation of Work
- 5 point

# Tasks
- [ ] What needs to get done?

# Risks
What data can we search by (mmr, names, title...)?

# Notes
This is reliant on the Database having replays accessible through the API Gateway
