### ISSUE TITLE
As a general user, I want to see data on faceoff formations, so that I can see what faceoff formations and tactics work best for me and my teammates.

### ISSUE THREAD

**Issue by matt89201824** [stratosphererl/stratosphere#31]
# Acceptance Criteria
- [ ]  Website: when given a replay, each faceoff is assigned a tactical name/style
- [ ]  Overlay: after a match is concluded, a graph or general analysis of faceoff tactics is provided to the user

# Estimation of Work
- 19 points

# Tasks
- [ ] Research on what types of faceoff styles the RL user base could be split into
- [ ] Manually iterating through replays to assign styles to faceoffs for training data
- [ ] Splitting collected data into training, testing, and validation sets
- [ ] Training and testing various ML models to see which may work best for our needs (trial and error)
- [ ] Potentially: gaining user / outside feedback on whether our model feels accurate and useful

# Risks
Defining what constitutes a "faceoff;" first five seconds of play at start or after goal? Until ball in offensive/defensive third? etc.
How faceoff styles can be split up may be largely subjective
Lots of time needed to iterate through replays (potentially gathered from ballchasing)
What about fakes? When you consider it a face off? Could be more like possession? Goes towards your teammate considered a win.

# Notes
Wayton's videos (I think there are two) on faceoffs may give us a starting point for considering how to split/group faceoff styles
Splitting faceoff styles by gamemode (1v1, 2v2, etc.) may be useful
Using an ML model which clusters without labeled data (unsupervised learning) may best help us group faceoff styles

**Comment by matt89201824** [comment]
Aggregation of replays? A single replay may not be essentially interesting or useful.
