### ISSUE TITLE
[EPIC] General users should see post-game and on-website identification of player traits with the overlay and website, respectively

### ISSUE THREAD

**Issue by matthew-jugovic** [stratosphererl/stratosphere#32]
## Description
If using our website, after uploading a replay file players should be able to see player traits for each player in the replay as identified via ML model. If using our overlay, after a match has concluded players should be able to see player traits for each player in the match as identified via ML model. This is so players can get a better idea what of playstyles work best in general, their own traits, that of their teammates, and which types of players they work well with and not so well with.

## Estimation of Work
5 points

## Story(s)
This is where you would link other stories that pertain to this epic.
- [ ] #49
- [ ] As an overlay user, I want to see player traits for everyone in a match so I can see what playstyles I work well with and not
- [ ] As a Web developer, I want to receive a data structure containing player trait data for every player in a replay when it (or its respective JSON file) passed to our ML program so I can display it to website users
- [ ] As an Overlay developer, I want to receive a data structure containing player trait data for every player in a match after the match concludes and match data is passed to our ML program so I can display it to overlay users

## Affected Personas
- Website users (see traits after replay upload)
- Overlay users (see traits after playing match)
- ML engineers (need to research, train, test ML models for this use case; consider what trait categories are best to use)
- Web developers (need to effectively portray trait data to user on website)
- Overlay developer (need to effectively portray trait data to user in overlay)

## What are we planning to do about it?
1. ML engineer will research various ML models which may be helpful for this task (say, unsupervised models)
2. ML engineer will create various models to train, test, and validate
        - Will determine what data in replays would be useful for determining player traits
        - If using supervised model: will manually assign player traits for a (large?) set of replays 
        - If using supervised model: will need to determine what trait separations are useful and not
        - Will use data gathered (from replays) to train the models
        - Will test and validate the models against
3. Based on model results, ML engineer will choose a model for our ML program to use
4. ML engineer will implement that model so it can be passed a replay, replay JSON, or match data and output a data structure containing player trait data
5. Web developer will call ML program by passing it a replay or replay JSON file
6. Web developer will use data structure received and successfully display player trait data to website user
7. Overlay developer will call ML program by passing it match data (or a replay/replay JSON file?)
8. Overlay developer will use data structure received and successfully display player trait data to overlay user post-match

## How will we measure success?
General:
1. When passed replay or match data (in JSON format?) our ML program will identify some amount of player traits for each player given their play in the replay/match
2. If supervised: The ML model we use will accurately predict player traits a particular amount of the time (say, >90%?)
3. [Would like to define some sort of "our presentation looks presentable" but not sure how to quantify this]

Website:
1. Calls our ML model while passing it a replay or replay JSON
2. When our ML model returns a data structure of player traits in a replay, this will be presented to the website user

Overlay:
1. Calls our ML model while passing it match data (a replay?)
2. When our ML model returns a data structure of player traits in a match, this will be presented to the overlay user

## Risks

For overlay, do we automatically save a replay immediately, upload it, parse, and return the data structure from ML, or have match data, and have the ML calculating in realtime?
Is there enough time to upload data to server, have ML work with it, and return player trait information while player's are "dancing" after a match?
