### ISSUE TITLE
[EPIC] General users should see post-game and on-website identification of faceoff formations with the overlay and website, respectively

### ISSUE THREAD

**Issue by matthew-jugovic** [stratosphererl/stratosphere#33]
## Description
If using our website, after uploading a replay file users should be able to see faceoff formation data for the match as gathered generally and as identified via ML model. If using our overlay, after a match has concluded users should be able to see faceoff formation data for the match as gathered generally and as identified via ML model. This is so player can get a better idea of what faceoff formations work best in general, work best for them and their teammates, etc.

## Estimation of Work
5 points

## Story(s)
- [ ] As a website user, I want to see faceoff formation data for a match when I upload a replay so I can see which work best
- [ ] As an overlay user, I want to see faceoff formation data for a match when one has concluded so I can see which work best
- [ ] As a Web developer, I want to receive a data structure containing faceoff formation data for a match when I pass our ML program a replay so I can display it to website users
- [ ] As an Overlay developer, I want to receive a data structure containing faceoff formation data for a match when I pass our ML program match data so I can display it to website users

## Affected Personas
- Website users (see data after replay upload)
- Overlay users (see data after playing match)
- ML engineers (need to research, train, test ML models for this use case; may consider what formation categories are best to use)
- Web developers (need to effectively portray formation data to user on website)
- Overlay developer (need to effectively portray formation data to user in overlay)

## What are we planning to do about it?
1. ML engineer will research various ML models which may be helpful for this task (say, unsupervised models)
2. ML engineer will create various models to train, test, and validate
    - Will determine what data in replays would be useful for determining formation categories
    - If using supervised model: will manually assign formation categories for a (large?) set of replays
    - If using supervised model: will need to determine what formation category separations are useful and not
    - Will use data gathered (from replays) to train the models
    - Will test and validate the models against
3. Based on model results, ML engineer will choose a model for our ML program to use
4. ML engineer will implement that model so it can be passed a replay, replay JSON, or match data and output a data structure containing faceoff formation data
5. Web developer will call ML program by passing it a replay or replay JSON file
6. Web developer will use data structure received and successfully display faceoff formation data to website user
7. Overlay developer will call ML program by passing it match data (or a replay/replay JSON file?)
8. Overlay developer will use data structure received and successfully display faceoff formation data to overlay user post-match

## How will we measure success?
General:

1. When passed replay or match data (in JSON format?) our ML program will identify how many faceoffs took place in the match and identify for each team in each faceoff the faceoff formation they used
2. If supervised: The ML model we use will accurately predict player faceoff formations a particular amount of the time (say, >90%?)
3. [Would like to define some sort of "our presentation looks presentable" but not sure how to quantify this]

Website:

1. Calls our ML model while passing it a replay or replay JSON
2. When our ML model returns a data structure of faceoff formation data in a replay, this will be presented to the website user

Overlay:

1. Calls our ML model while passing it match data (a replay?)
2. When our ML model returns a data structure of faceoff formation data in a match, this will be presented to the overlay user

## Risks
Same as with issue #32

**Comment by matt89201824** [comment]
Note: something for the overlay in general later, can be to select a "category" to show after a match. Faceoffs, shots, etc.
