### ISSUE TITLE
As a general user, I want to see general data about kickoffs, so that I can know how if its an area I need to improve in.

### ISSUE THREAD

**Issue by matthew-jugovic** [stratosphererl/stratosphere#37]
# Acceptance Criteria
- [ ] Website: after uploading a replay, a website user would be able to see data about kickoffs in the match, including: (1) how many faceoffs there were, (2) how many of them were "won" by their team vs the other, and (3) the positioning of players through the kickoff (drive up, hit, after, etc.)
- [ ] Overlay: after a match, an overlay user would be able to see data about kickoffs in the match, including the same as for the website

# Estimation of Work
3 points (website)
5 points (overlay)

# Tasks
- [ ] Website: write a method which accepts a parsed replay or data structure and outputs interactive graphics which present kickoff data on a per-kickoff and aggregate basis for the match
- [ ] Overlay: write a method which accepts match data or data structure and outputs interactive graphics which present kickoff data on a per-kickoff and aggregate basis for the match

# Risks
- Providing the faceoff data in the post-match screen may cause clutter, especially if lots of other items are there; we may want to create some sort of drop down selection menu for users to select between various data, including faceoff, goals, shots, etc. This however would be its own user story I image
- Should the method used on the website/overlay accept a parsed replay as input, or a simpler data structure be provided which the website/overlay can more easily access than having to traverse the JSON?

# Notes
Either a parsed replay (for website) or current match data (for overlay) is needed as input

**Comment by cchurness** [comment]
The overlay is probably going to have to look at different data than the website. I'm not going to elaborate because I don't quite know how much different it is yet. This comment is more of an extension of your second risk.

**Comment by matt89201824** [comment]
Overlay should be 2D representation of faceoffs?
