### ISSUE TITLE
As a general user, I want to see general data on how goals were scored, so that I can how to improve my offensive capabilities.

### ISSUE THREAD

**Issue by matt89201824** [stratosphererl/stratosphere#38]
# Acceptance Criteria
- [ ] Website: after uploading a replay, a website user can see data concerning goals in the replay, including: (1) how many were scored, (2) where the ball was when scored, (3) the position of the ball when it was shot, (4) the position of the ball when it was last touched, and (5) the formation of all players (with team color identified) any time up to five seconds before the goal was scored, implemented by a scroll bar
- [ ] Overlay: same as above, but perhaps with less functionality; perhaps only the position of the ball when it was shot and the formation of all players up to five seconds before w/ scroll bar

# Estimation of Work
- TBA

# Tasks
- [ ] Website & Overlay individually: Implement a method which accepts parsed replay data or data structure and outputs the data requested by the acceptance criteria for each part of the platform
- [ ] Website & Overlay individually: Allow the user to view the position of all players up to five seconds before the goal was scored

# Risks
- Cluttering the post-match screen is, once again, an issue

# Notes
This user story may build upon user story #26: https://github.com/stratosphererl/stratosphere/issues/26

**Comment by cchurness** [comment]
How will the position of the ball when shot differs from the position of the ball at the last touch? What were you thinking of showing on the overlay? Since drawing 3D objects while in-game sounds difficult, I would suggest a minimap type of thing showing player positions in a 2D way.

**Comment by matt89201824** [comment]
Good idea on the 3D vs 2D idea. 2D would be better for overlay I am sure. Also, you're right that where the ball was when shot and last touched would likely be the same. I suppose my mind was thinking of times where someone shoots and the ball is own-goaled or otherwise deflected
