### ISSUE TITLE
As a developer, I want an API gateway, so that I can fetch from and send data to.

### ISSUE THREAD

**Issue by chrishollandaise** [stratosphererl/stratosphere#4]
# Acceptance Criteria
- [x] Given a user has data stored in a service
- [x] When the user makes a request to the API gateway
- [x] Then the gateway will fetch the data from the service

# Estimation of Work
- 8 points

# Tasks
- [x] Learn about apollo-server
- [x] Learn about connections to databases and other sources
- [x] Do more research

# Notes
Currently, communication as diagrammed during our meeting on 9/21/22 shows others services can directly communicate with each other. How can this be done? Is this the best way of doing it? How can this be achieved using GraphQL, what other tools might you be missing?
