### ISSUE TITLE
As a user, I want to see my game play out automatically before my eyes, so that I can marvel at my greatness.

### ISSUE THREAD

**Issue by cchurness** [stratosphererl/stratosphere#40]
# Acceptance Criteria
- [ ] Given that we can view frames from a replay
- [ ] When the user starts playback
- [ ] Then consecutive frames play out

# Estimation of Work
- 2 points

# Tasks
- [ ] What needs to get done?

# Risks
Getting all the network data from the replay quickly.
Playing the replay without delay.

# Notes
I believe it's assumed some replay stuff is already done.

**Comment by matt89201824** [comment]
Tasks could include:
1. Grab replay file from filepath (accessed by ID from DB)
2. Send replay file to parser (to get JSON)
3. Present JSON data frames on interactive timeline
4. Have selecting a particular frame show in an 3D render
    - This would involve having the meshes, etc. you mentioned in the epic
5. Allow for play/pause functionality of 3D render, instead of just selecting a frame manually

**Comment by matt89201824** [comment]
May also want a speed option (real-time, half real-time, etc.)
