### ISSUE TITLE
As a developer, I want to have a scene that displays meshes and textures, so that I can better piece together more complicated imagery.

### ISSUE THREAD

**Issue by cchurness** [stratosphererl/stratosphere#41]
# Acceptance Criteria
- [x] Given that we have a scene
- [x] When the scene is updated regularly
- [x] Then a variety of meshes relevant to Rocket League entities will display

# Estimation of Work
- 2 points

# Tasks
- [x] Create a scene manager
- [x] Throw in some meshes
- [x] Add some light
- [x] Include controls and camera
- [x] Boom

# Risks
Make sure the scene fits nicely within our website and is not distorted by resizing.

# Notes
We need meshes to represent the cars, ball, and boost pads.

**Comment by matt89201824** [comment]
Nothing to add here. Step four in my comment on issue #40 (https://github.com/stratosphererl/stratosphere/issues/40) is the implementation of this user story.

**Comment by cchurness** [comment]
Since we can link issues to other issues, that might be a good thing to do for these interconnected issues.
