### ISSUE TITLE
As a user, I want to see a timeline related to a replay, so that I can better navigate the replay viewer.

### ISSUE THREAD

**Issue by cchurness** [stratosphererl/stratosphere#42]
# Acceptance Criteria
- [ ] Given that there is an interactive bar at the bottom of the replay with icons indicating important events
- [ ] When the user clicks on a location
- [ ] Then the replay skips to the relevant frame

# Estimation of Work
- 2 points

# Tasks
- [ ] What needs to get done?

# Risks
What is not known? Potential roadblocks?

# Notes
This is likely one of the last issues to be completed for the 3D model

**Comment by matt89201824** [comment]
Again, not much to add here, though do consider expanding on the tasks section potentially with the ideas I provided in my comment on issue #40
