### ISSUE TITLE
[EPIC] WebApp Population Statistics

### ISSUE THREAD

**Issue by chrishollandaise** [stratosphererl/stratosphere#44]
## Description
Within the web app, there should be a separate page that shows varying statistical visualizations of the state of rocket league play. The visualizations can break down the population by the aggregate of replays, group them by rank, or any other meaningful categorization. These visualizations should be an aggregate of all user replays and should be anonymized. This epic is trying to address any curiosity users might have about rocket league stats as a community and might want to see a broader picture of the state of play. The purpose of this epic is to provide more holistic data analysis and provide quick and meaningful visualizations that can help answer some questions the user might have. This is important because it can provide useful information that can be broken down in a larger group setting--answers questions about what would the average player or rank perform?

## Story(s)
- [ ] As a user, I want to be able to filter aggregate replay data based on the criteria (e.g. eason, rank, and game mode),  so that I can get detailed and specific with my search
- [ ] As a website user, I want to be able to see a statistical breakdown of a rocket league distribution on various factors (e.g. scores, goals, assists) so that I can see how the community is performing.
- [ ] As a user, I want to be able to see a skill rating distribution (able to filter it by game mode), so that I can understand where my skill fits into the population.

## Affected Personas
- Website Users
- Web Developers

## Overall Risks
- Not knowing how to present the data in a meaningful way
- Not knowing what kind of data would be useful to the community
- Not able to generate visualizations that can help address more than one question the user might have.
- Not able to present the data in an engaging way for users to want to explore

## What are we planning to do about it?
The scope of the design and engineering work required for this project includes designing an interface to visualize data, designing visualizations to be displayed on the interface, and engineering the interface and visualizations. 

## How will we measure success?
- [ ] The web page is easy to navigate
- [ ] The visualizations are easy to understand
- [ ] The visualizations are visually appealing
- [ ] The user was able to follow along with the visualizations
- [ ] The visualizations answered user's questions about the data
