### ISSUE TITLE
[EPIC] Identification of Mechanics in Replay

### ISSUE THREAD

**Issue by chrishollandaise** [stratosphererl/stratosphere#45]
## Description
Given a replay, a user can be able to see the types of mechanics they used in that game (e.g. half flip, flicks, dribbling). This epic is trying to address the need for a mechanism to identify RL mechanics in play. This would be important because it would allow for a better understanding of the user's play for a given game session and it would allow players to be able to identify the mechanics they are playing against in order to make better decisions. For web development, we can provide statistical visualizations and high-level overviews of the user's play. This can provide the basis for other features like the identification of playstyles.

## Story(s)
This is where you would link other stories that pertain to this epic.
- [ ] As a web developer and overlay developer, I want a model or some function that is able to identify mechanics for a given replay, so that incorporate this information into the user.
- [ ] As a user, I want to see tags of mechanics used in a replay, so that I can analyze my play and technique.
- [ ] As a user, I want to be able to tag what mechanics I used in that replay so that I can properly manage my replays.
- [ ] As a DevOps/MLOps engineer, I want the model to continuously train and learn, so that it can provide accurate results.
- [ ] As an overlay developer, I want to have a lite-version of what the website offers so that users can easily access that information within the game.

## Affected Personas
- Users
- Web Developers
- ML Engineers
- DevOps/MLOps Engineers
- Overlay Developer

## Estimation of Work
40+ hours (14+ days)

## Overall Risks
- Can we identify mechanics based on algorithms or do we need an ML model for this? Which one would be easier to maintain, more accurate, etc?
- What ML models would be used for this? When would it identify when a mechanic starts and ends? Has to be pretty granular?
- If we choose an ML model, how can we make it so that it can be continually trained with more replay datasets? MLOps pipeline?

## What are we planning to do about it?
The design and engineering work required for this project would be to develop an algorithm or ML model that could accurately identify mechanics in a replay. This would require a lot of work in terms of data collection, feature engineering, and model development/tuning. Additionally, there would need to be a way to continuously train and update the model as new replays are collected. This would likely require some sort of MLOps pipeline. Finally, the overlay and website developers would need to create a way to display this information to users in an easily digestible way.

### Users

- The ability to see tags of mechanics used in a replay, so that they can analyze their play and technique.
- The ability to be able to tag what mechanics they used in that replay so that they can properly manage their replays.

### Web Developers

- A model or some function that is able to identify mechanics for a given replay, so that they can incorporate this information into the user.

### ML Engineers

- A model or some function that is able to identify mechanics for a given replay, so that they can incorporate this information into the user.
- The ability to make the model continuously train and learn, so that it can provide accurate results.

### DevOps/MLOps Engineers

- A model or some function that is able to identify mechanics for a given replay, so that they can incorporate this information into the user.
- The ability to make the model continuously train and learn, so that it can provide accurate results.

### Overlay Developer

- A lite-version of what the website offers so that users can easily access that information within the game.

**Comment by chrishollandaise** [comment]
Matt asked: 
> Do remember, for this issue, we may have a lot of mechanics which we could identify manually (ex. if a player hits the ball, the ball hits the backboard, and the player then hits the ball in without x seconds, it is a double-tap goal

Yeah, I do remember. I think we'll need to add notes to this page of all the mechanics we can think of if we wanted to go through the algorithmic route.
