### ISSUE TITLE
As a developer, I want an entity component system, so that I can develop 3d visuals "cleanly".

### ISSUE THREAD

**Issue by cchurness** [stratosphererl/stratosphere#48]
# Acceptance Criteria
- [x] Given an entity component system exists
- [x] When I add a new entity
- [x] Then I can append relevant components to said entity

# Estimation of Work
- 8 hours (3-4 days)

# Tasks
- [x] Create an ECS class
- [x] Create a bunch of tables/maps to store data
- [x] Create Entity and Component methods
- [x] Ability to edit data in a component
- [x] Easy implementation of systems

# Risks
What is not known? Potential roadblocks?

# Notes
ECS is probably overkill and not necessary. I hate hindsight.
