### ISSUE TITLE
As a developer, I want to store replay file in a database, so that I can retrieve it for later.

### ISSUE THREAD

**Issue by chrishollandaise** [stratosphererl/stratosphere#5]
# Acceptance Criteria
- [ ] Given a request to store replay data
- [ ] When the data is stored in the database
- [ ] Then the data should be easily accessible for later retrieval

# Estimation of Work
- TBA

# Tasks
- [ ] Come up with a valid schema (e.g. proper types, well organized)
- [ ] SQL commands be to retrieve and store the data and file?
- [ ] Get a PostgresSQL up and running
- [ ] Create a single table with 3 columns (primary key (id), replay file, and a some data from the match)

# Notes
What makes sense for the database to store? We currently have the replay file and the match data associated with it.

Because replay files are too big to store in as an entry in a SQL database, you will have to deal with the file system. Can two replay files have the same file name? What will happen? How does this impact the database, does it introduce redundancies and waste?

**Comment by chrishollandaise** [comment]
Hey @matt89201824, I am reviewing your work. First of all, thanks for completing the first part of this task and providing documentation about how to set up the database.

Separating each SQL statement in its own file is great for readability and understanding the purpose. However,
I will need an `init.sql` file for the final product because I need to have it automatically create the database, so having all the SQL statements needed to initialize the database fully needs to be in one file. In addition, your instructions need to be in a markdown file rather than a text file. 

**Questions:**
1. [Is it always the case that the filename is a maximum of 120 characters?](https://github.com/stratosphererl/stratosphere/blob/91385bc00bc2116737eecccb20751e87ca99c31e/database/2_ActualCreateTable.sql#L3)
2. How would you want to go about testing your database? Unit testing in particular? How would you go about making some mock data for us to test things on? (These questions are going to prime you for the next sprint, you don't have to add any of these things to Sprint 1)

**Other remarks:**
- I am planning that we will have a production and developer database. This is because if we ever get actual real-life users, we do not want any of our tests affecting production. Any of our tests on the database end would happen on the dev database. 

**Tasks summarized:**
- [ ] Create an `init.sql` file that creates the database and initializes the necessary tables
- [ ] `instructions.txt` needs to be renamed `README.md` and follow proper [MD conventions ](https://www.markdownguide.org/cheat-sheet/) (e.g. has headers, bold where you need to, code blocks, etc)
- [ ] [1_SupplementDropDatabase.sql](https://github.com/stratosphererl/stratosphere/blob/matt-branch/database/1_SupplementDropDatabase.sql), [3_ActualInsertMock.sql](https://github.com/stratosphererl/stratosphere/blob/matt-branch/database/3_ActualInsertMock.sql), [4_ActualSelectAll.sql](https://github.com/stratosphererl/stratosphere/blob/matt-branch/database/4_ActualSelectAll.sql), [5_TemplateGetDatavalue.sql](https://github.com/stratosphererl/stratosphere/blob/matt-branch/database/5_TemplateGetDatavalue.sql), [6_TemplateGetFilename.sql](https://github.com/stratosphererl/stratosphere/blob/matt-branch/database/6_TemplateGetFilename.sql), and [7_TemplateInsertData.sql](https://github.com/stratosphererl/stratosphere/blob/matt-branch/database/7_TemplateInsertData.sql) **contents need to be migrated into the README.md and then each file removed.** You can put them under a section called "Documentation." So you should only have `init.sql` and `README.md` left.
- [ ] Please come up with a user and password that we can use to get access to the database. **DO NOT POST IT ON GITHUB, give me the password either through private DMs or IRL.**

**Comment by matt89201824** [comment]
@chrishollandaise 
1. Filenames are not always 32 characters, that was simply but can be. The format I was thinking we would go with replay file names is, when one is uploaded by a website user, we would rename their replay from the 32-letter-and-number name to a filename that is <username><datetime>.replay (ex. Novarchite20221008072242.replay). With 120 char length, usernames could be 99 char long, with datetime taking 14 long and .replay accounting for the last 7 chars (99+14+7=120).
2. I would prefer to use manual testing, but would be able to make a mock SQLite DB
