### ISSUE TITLE
As a website user, I want to have a neatly organized menu, so that I can easily navigate the website.

### ISSUE THREAD

**Issue by cchurness** [stratosphererl/stratosphere#55]
# Acceptance Criteria
- [ ] Given the website has a navigation bar
- [ ] When the user selects an item on the nav bar
- [ ] Then the user is redirected elsewhere

# Estimation of Work
- Implementation: 3-4 hrs (1-2 days)
- Design: 2 hrs (1 day)
_Note: Implementation and Design may or may not happen simultaneously_

# Tasks
- [ ] What needs to get done?

# Notes
The purpose of this issue is to begin a common theme or design when further developing the website.
This is not a very strict issue, it is meant to be rather open-ended and possibly changed to be more specific later.

Make a wireframe (drawing) and sitemap (where all the possible pages)

**Comment by matt89201824** [comment]
Figma wireframe: https://www.figma.com/file/r89tHx7ODN0ieNm4oJFq8P/Stratosphere?node-id=0%3A1&t=Oetj5hCKviyTvo54-1
General sitemap: https://i.imgur.com/70LjXrl.jpeg
