### ISSUE TITLE
As a website developer, I want to have easy access to specific information in a replay, so that I can access important replay information without the headache of searching large JSONs.

### ISSUE THREAD

**Issue by cchurness** [stratosphererl/stratosphere#56]
# Acceptance Criteria
- [ ] Given API calls can be made to the parser
- [ ] When the developer requests specific replay data
- [ ] Then the parser will return a neatly formatted "small" JSON

# Estimation of Work
- 6 hrs (2-3 days)
_note: This is a very rough guess, I don't know what goes into the gql server_

# Tasks
- [ ] Create webapp tools to make common requests easily
- [ ] Do gql stuff I don't understand yet
- [ ] Make the parser return specific information

# Risks
This requires work to be done in three different places:
webapp, parser, and gql directories.

# Notes
- Do we want to extend the parser's responsibilities by organizing a replay into something more meaningful
