### ISSUE TITLE
As a user, I want to be able to hover over the heatmap to see more information about that shot, so that I can satisfy my curiosity and get more context.

### ISSUE THREAD

**Issue by chrishollandaise** [stratosphererl/stratosphere#57]
# Acceptance Criteria
- [ ] Given I have a replay that has a heatmap component
- [ ] When I hover over a one of the contours
- [ ] Then I should see a tooltip pop up and be able to see information about those goals

# Estimation of Work
- 3-4 hours

# Tasks
- [ ] What needs to get done?

# Risks
- The heatmap component would need to be changed to not just store x,y,z  coordinates, it would need to store more information about the player and when the goal was struck, etc.

# Notes
- Should be like a tooltip on hover. If there were multiple goals should be displayed but in separate tabs, so I can just focus on a single player at a time.
- It should be a tooltip component, or alternatively can be something a part of the heatmap component.
