### ISSUE TITLE
[EPIC] As a general user, I want to see data on faceoff formations, so that I can see what faceoff formations and tactics work best for me and my teammates.

### ISSUE THREAD

**Issue by matthew-jugovic** [stratosphererl/stratosphere#58]
## Description
This epic is trying to address the lack of faceoff analysis that exists in other RL platforms. Once this epic is complete, users should be able to see, after uploading a replay or playing a match in Rocket League, statistics or graphical representation(s) of what types of faceoffs were in the match, how many, how many won faceoffs per team, etc.

## Story(s)
- [ ] As a developer, I want to know what types of faceoffs are used often in Rocket League so I have information to build an accurate ML around (this is a research user story)
- [ ] As a website / overlay developer, I want a model which takes a replay JSON as input and outputs the types of faceoffs used in the match stored in that JSON
- [ ] Website: when given a replay, a graph or general analysis of faceoff tactics is provided to the user
- [ ] Overlay: after a match is concluded, a graph or general analysis of faceoff tactics is provided to the user (if graph is desired)

## Affected Personas
- Website users, overlay users (potentially), website developers, overlay developers, ML engineers

## What are we planning to do about it?
- Researching what faceoff styles are usually used currently across Rocket League
- Gathering replay data
- Determine what variables would be useful from replays / replay JSONs for determining faceoff groupings
- Pulling faceoff data from replays for building of model(s)
- Splitting faceoff data into training, testing, and validation sets
- Training various models to see which best fit our needs and has the best results for faceoff data (model should likely use unsupervised learning)
- Potentially: gaining user / outside feedback on whether our models feels accurate

## How will we measure success?
- Having an ML model which uses unsupervised learning and potentially semi-supervised learning in order to group faceoffs into a particular category or set of categories
- Website and overlay users being able to see such data for their match(es) after uploading/finishing the match
