### ISSUE TITLE
As a developer, I want an ML service, so that I get not-so-random predictions from

### ISSUE THREAD

**Issue by chrishollandaise** [stratosphererl/stratosphere#6]
# Acceptance Criteria
- [x] Given some input data
- [x] When the ML model receives the input data
- [x] It makes a _not-so-random_ prediction 

# Estimation of Work
- 0 point

# Tasks
- [x] Create the project using poetry
- [x] Accept some arbitrary input
- [x] Produce some random value
- [x] For now print said value to standard output

# Notes

**Comment by chrishollandaise** [comment]
Hey @cchurness, I am reviewing your work. Thanks for completing this incredible user story.

## Feedback
Great job on including the tests folder, using poetry, and having a general entry script.py file. While [__init__.py](https://github.com/stratosphererl/stratosphere/blob/caleb-branch/machine-learning/machine_learning/__init__.py) is great for seeing what the `rl_trained_models` do, I need to have the models be accessible via CLI. So, I'd need you to use [argparse module](https://docs.python.org/3/library/argparse.html), and have each model accessible via the command line. So an example would be `stratosphereml <model_name> <input> -o <filepath>`. Can either return option as stdout or in a specified output file.

## Questions:

- What kind of tests were you imagining would be in the tests folder? [Here is a quick look-up of all the tests](https://www.atlassian.com/continuous-delivery/software-testing/types-of-software-testing). This will be helpful to know the next sprint with data gathering and validation.

## Other remarks:
- None

## Tasks summarized:

- [ ] Create a CLI interface for the ML models.

**Comment by cchurness** [comment]
I don't know what kind of testing I'm thinking of for future sprints. For this sprint, testing other than manually is fairly redundant. For the most part, the testing folder was established automatically by poetry.
