### ISSUE TITLE
As a User, I want to see how my teams offense/defense stacks up related to the opponents, so that I can better understand the pressure of my team.

### ISSUE THREAD

**Issue by cchurness** [stratosphererl/stratosphere#66]
# Acceptance Criteria
- [ ] Given this component is enabled
- [ ] When players move around the field their positions are kept track of
- [ ] Then a meter on the side of the screen shows players a meter to represent "calculated" aggression

# Estimation of Work
- 3 to 6 hrs

# Tasks
- [ ] Add to the settings menu to enable/disable
- [ ] Create a new minimal window that displays progress bars
- [ ] Collect data for every game tick (counters)

# Risks
I'm assuming multiple meter-type graphics will be shown, we don't know how many we'll show which means the estimation of work will vary depending on how many different meters there are.

My current thought is to gain data for every game tick which may be stupid. It would be a good idea to use the function scanner to find a better less frequent function to hook when updating player information.

# Notes
I explained this terribly in the acceptance criteria, if you're trying to understand what I'm talking about, look at ballchasing. I want to do something similar to what they do with tracking what percentage of time players are on opponents' sides.
