### ISSUE TITLE
As a user, I want to see aggregated match data in the menus, so that I can better understand my play over a larger span of time.

### ISSUE THREAD

**Issue by cchurness** [stratosphererl/stratosphere#67]
# Acceptance Criteria
- [ ] Given the user opens an aggregate data window
- [ ] When the game queries our database
- [ ] Then aggregate data gotten from the database displays to the user

# Estimation of Work
- 10 hrs

# Tasks
- [ ] I don't know yet

# Risks
This either needs to contain other user stories relating to other microservices, or it needs to wait for other stories. (It has prerequisites)

# Notes
This will likely have work done on the overlay, the database, the API, and possibly the parser.
