### ISSUE TITLE
As a user, I want to see a complete set of statistical data from a replay, so that I can analyze individual player's effort and the general match outcome.

### ISSUE THREAD

**Issue by cchurness** [stratosphererl/stratosphere#69]
# Acceptance Criteria
- [ ] Give the user uploads or selects a replay
- [ ] When the parsed information returns from the parser/db
- [ ] Then the user sees information pertaining to scores, goals, assists, saves, shots, percentages of time spent in parts of the field, etc

# Estimation of Work
- 8 hrs (less if the parser is complete)

# Tasks
## Parser User Stories
- [ ] Parse information pertaining to scores, goals, assists, saves, shots
- [ ] Parse information pertaining to player positions
## Webapp Tasks
- [ ] Present a table of information that displays scoreboard information
- [ ] Give information of time players spend in particular parts of the field
_note: This information may be attached to heatmaps_

# Risks
Parser implementation is a prerequisite

# Notes
What I listed is very similar to what ball-chasing provides. This stuff is important for our website, but we may want to think of ways to be original.
