### ISSUE TITLE
As an operations engineer, I want to be able to deploy my apps with a click of a button. 

### ISSUE THREAD

**Issue by chrishollandaise** [stratosphererl/stratosphere#7]
# Acceptance Criteria
- [ ] Given that I have an app that is ready for production
- [ ] When I click the "Deploy" button
- [ ] Then my app is deployed to a production server

# Estimation of Work
- TBA

# Tasks
- [ ] What needs to get done?

# Notes
Currently, we are going to split this project into services and overlay mod. The overlay mod has its own build systems involved, and would then need to be deployed on its own pipeline.
