### ISSUE TITLE
As a user, I want to see names and information about my stored replays, so that I can better manage my replays and upload specifically what I want.

### ISSUE THREAD

**Issue by cchurness** [stratosphererl/stratosphere#70]
# Acceptance Criteria
- [ ] Given the user can open a new window for replay management
- [ ] When the user selects a replay
- [ ] Then they get information about that replay
- [ ] And the user can see a button to upload the selected replay
- [ ] When the user clicks the upload button
- [ ] The replay gets uploaded to our db to be viewed on the front-end later

# Estimation of Work
- 8 to 10 hrs

# Tasks
- [ ] Figure out cpprp
- [ ] Parse replays in our plugin
- [ ] Display information in a new window
- [ ] Move uploading features to new window

# Risks
We need to do this additional parsing in the overlay on the client's machine.
Make take a bit of learning to understand cpp and getting/using new dependencies.
