### ISSUE TITLE
As a user, I want to authenticate myself via Steam on the website, so that I can get access to my account. 

### ISSUE THREAD

**Issue by chrishollandaise** [stratosphererl/stratosphere#71]
# Acceptance Criteria
- [ ] Given that I am a user of the website,
- [ ] When I want to authenticate myself,
- [ ] Then, I should be able to do so via  Steam.

# Estimation of Work
- 6 points

# Tasks
- [ ] Set up an authentication service that will connect Steam provider servers to get user identity
- [ ] GraphQL needs to do validation and handle sending the token to the user
- [ ] Will need to set up cookies on the frontend to help user stay logged in even after browser is closed
- [ ] #21

# Notes
-
