### ISSUE TITLE
As a developer, I want to be able to have a CI server, so that it automatically builds and tests my code every time.

### ISSUE THREAD

**Issue by chrishollandaise** [stratosphererl/stratosphere#8]
# Acceptance Criteria
- [ ] Given a developer submits a pull request
- [ ] When they check it into the CI server
- [ ] Then the CI server should build and test the code automatically

# Estimation of Work
- 4 point (15 hours)

# Tasks
- [ ] What needs to get done?

# Notes
Because we have a monorepo, we need to make sure the build system doesn't take too long. Also, need to look into the costs of such service.
