### ISSUE TITLE
As a developer, I want to have a better experience developing on Docker, so that I can be more productive.

### ISSUE THREAD

**Issue by chrishollandaise** [stratosphererl/stratosphere#80]
# Acceptance Criteria
- [ ]  The developer environment is enhanced with the implementation of hot reloading on containers
 - [ ] Environment variables are utilized to make it easier for developers to work with the containers
 - [ ] Docker templates are used to simplify the process of working with Docker
 - [ ] Documentation on troubleshooting techniques is provided to assist developers in resolving issues with the enhanced developer environment

# Estimation of Work
- 3 hours

# Tasks
- [ ]  Hot reloading is implemented on the containers
- [ ]  Environment variables are used
- [ ]  Make use of docker templates
- [ ]  Documentation on troubleshooting techniques

# Risks
Changes made to the developer environment may introduce new bugs or errors

# Notes
