### ISSUE TITLE
[SPIKE] - Integrating Testing 

### ISSUE THREAD

**Issue by chrishollandaise** [stratosphererl/stratosphere#81]
# Context
To improve the quality and reliability of our software, we want to integrate unit testing and integration testing in our micro-service architecture, which currently has no testing in place.

# Timebox
1 day

# Tasks
- [ ] Research and evaluate different unit,component, and integration testing frameworks for javascript and python
- [ ]  Identify the critical and high-risk areas of the software that need to be tested
- [ ]  Create a plan for implementing testing in the software

# Notes
