### ISSUE TITLE
As a developer, I want to route all requests through GraphQL server, so that I do things properly.

### ISSUE THREAD

**Issue by chrishollandaise** [stratosphererl/stratosphere#84]
# Acceptance Criteria
- [x]  All requests for data from the frontend are routed through the GraphQL server
- [x]  The GraphQL server is properly configured to handle the requests to and from the replay service
- [x]  The implementation is tested and validated to ensure that data is properly filtered and parsed before being sent to the frontend

# Estimation of Work
- 6 points

# Tasks
- [x] For each service, a schema needs to be made to make sure the data from a service agrees with the format.
- [x] Each service also needs resolvers to actually get the data.

# Risks
Incorrectly configuring the GraphQL server may result in poor performance or unexpected behavior

# Notes
