### ISSUE TITLE
As an operations engineer, I want to be able to monitor the health of my infrastructure in real-time, so I can prevent issues

### ISSUE THREAD

**Issue by chrishollandaise** [stratosphererl/stratosphere#9]
# Acceptance Criteria
- [ ] Given an application and infrastructure
- [ ] When the application and infrastructure are running
- [ ] Then the health of the application and infrastructure can be monitored in real-time.

# Estimation of Work
- TBA (10 hours)

# Tasks
- [ ] What needs to get done?

# Notes
Need to look into some options, integrating such services requires interactions from all services
