### ISSUE TITLE
As a Frontend Developer, I want to refactor filtering.tsx, so that my code is cleaner.

### ISSUE THREAD

**Issue by matthew-jugovic** [stratosphererl/stratosphere#91]
# Acceptance Criteria
- [ ] filtering.tsx has been refactored into using less duplicate code and uses more components and/or functions
- [ ] No new bugs have been introduced (whether syntax or logical)
- [ ] No easily identifiable refactoring opportunities remain in filtering.tsx

# Estimation of Work
- 2-3 hours

# Tasks
- [ ] Identify all sections of filtering.tsx that could be refactored for better code management / readability
- [ ] Implement refactoring of all sections identified, either into components or functions, etc.
- [ ] Make sure no new errors / bugs are introduced due to refactoring

# Risks
Potentially introducing new errors / bugs or unintended effects due to refactoring

# Notes
n/a
