### ISSUE TITLE
As a frontend developer, I want the database to have queries for population data, so that I can present population data to the end user.

### ISSUE THREAD

**Issue by matthew-jugovic** [stratosphererl/stratosphere#92]
# Acceptance Criteria
- [ ] Given the frontend developer calls the GraphQL API for population data, the API will query the required database(s) in order to obtain the population data and will then return such data to the service calling it

# Estimation of Work
- N/A

# Tasks
- [ ] Implement SQL queries which, when called, will obtain population data from our databases
- [ ] Allow GraphQL API to call Stats service which will call such SQL queries and obtain the data which the SQL queries would return
- [ ] GraphQL will then return the data to the service which is calling it

# Risks
I am personally not sure how to implement this in the GraphQL

# Notes
N/A
