### ISSUE TITLE
As a developer, I want our project to include multiple databases for authentication, machine learning, and parsing, so that I can we can cleanly organize our data.

### ISSUE THREAD

**Issue by matthew-jugovic** [stratosphererl/stratosphere#93]
# Acceptance Criteria
- [ ] DBs for Auth, ML, and Parser microservices are fully implemented and finalized, including their schema structure
- [ ] The GraphQL API can be called to query these DBs
- [ ] One of the above DBs (most likely parser DB) stores the filepath of replay / parsed replay files

# Estimation of Work
- N/A

# Tasks
- [ ] Implement and finalize schema for auth, ml, and parser DBs
- [ ] Add GraphQL API functionality to query these DBs
- [ ] Decide which DB will be storing the filepath and header information of replay / parsed replay files (parser to store?)
- [ ] Implement the above per decision

# Risks
Unsure how to add ability to query DBs via GraphQL API

# Notes
N/A
