### ISSUE TITLE
GET /replays

### ISSUE THREAD

**Issue by chrishollandaise** [stratosphererl/stratosphere#95]
# Acceptance Criteria
- [x] The API returns all replays
- [x] The API returns replays in a offset paginated format
- [x] The API allows for filtering of replays
- [x] The API returns the appropriate status code for successful requests and error cases
- [x] Tests are present that can check that API is working effectively

# Estimation of Work
- TBA

# Tasks

# Risks

# Notes
- Make sure to return the appropriate status codes, think of the edge cases.
