### ISSUE TITLE
GET /replays/{id}

### ISSUE THREAD

**Issue by chrishollandaise** [stratosphererl/stratosphere#96]
# Acceptance Criteria
- [x] The API returns the specific replay with the given ID
- [x] The API returns the appropriate status code for successful requests and error cases
- [ ] Tests are present, making sure that this endpoint is working effectively

# Estimation of Work
- TBA

# Tasks
- [ ] Test the endpoint for successful requests and error cases

# Risks
Inconsistencies in the replay data. We need to stick with a particular format, and have this available for the API gateway.

# Notes
Make sure to return the appropriate status codes. We can think of them.
