### ISSUE TITLE
GET /replays/user/{user_id}

### ISSUE THREAD

**Issue by chrishollandaise** [stratosphererl/stratosphere#97]
# Acceptance Criteria
- [ ] The API returns all replays belonging to the specific user with the given ID
- [ ] The API returns the appropriate status code for successful requests and error cases
- [ ] Tests are implemented and test appropriately 

# Estimation of Work
- TBA

# Tasks
- [ ] What needs to get done?

# Risks
The user service will probably be in implementation, so you'll need to mock until those services can communicate.

# Notes
- Make sure to return the appropriate status codes
