### ISSUE TITLE
DELETE /replays/{id}

### ISSUE THREAD

**Issue by chrishollandaise** [stratosphererl/stratosphere#99]
# Acceptance Criteria
- [ ] The API deletes the specific replay with the given ID
- [ ] The API returns the appropriate status code for successful requests and error cases
- [ ] API is given the proper authorization via the header to delete that replay (e.g. the person who owns that replay or admin)

# Estimation of Work
- TBA

# Tasks
- [ ] Test the endpoint for successful requests and error cases

# Risks
Authorization. The auth server might be functioning when this is being built, so it'd be best to have a mock.

# Notes
Consider security concerns when deleting the replay
